// Generated by CIRCT firtool-1.62.0
module fwft_sync_fifo_11(	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:19:7
  input        clock,	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:19:7
               reset,	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:19:7
               io_fifo_wio_wen,	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:29:12
  input  [9:0] io_fifo_wio_wdata,	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:29:12
  input        io_fifo_rio_ren,	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:29:12
  output [9:0] io_fifo_rio_rdata,	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:29:12
  output       io_fifo_rio_empty	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:29:12
);

  reg  [2:0]      vaild_data;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:57:28
  reg  [1:0]      w_addr;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22
  reg  [1:0]      r_addr;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:36:22
  reg  [9:0]      memory_0;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17
  reg  [9:0]      memory_1;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17
  reg  [9:0]      memory_2;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17
  reg  [9:0]      memory_3;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17
  wire [3:0][9:0] _GEN = {{memory_3}, {memory_2}, {memory_1}, {memory_0}};	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17, :49:24
  wire            r_en = io_fifo_rio_ren & ((|vaild_data) | io_fifo_wio_wen);	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:42:{29,53}, :57:28, :71:41
  wire            w_en = io_fifo_wio_wen & (vaild_data != 3'h4 | io_fifo_rio_ren);	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:{29,53}, :57:28, :70:41
  wire [9:0]      _GEN_0 = _GEN[w_addr];	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22, :49:24
  wire [1:0]      _GEN_1 = {w_en, r_en};	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29, :42:29, :58:11
  always @(posedge clock) begin	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:19:7
    if (reset) begin	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:19:7
      w_addr <= 2'h0;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22
      r_addr <= 2'h0;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22, :36:22
      vaild_data <= 3'h0;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:57:28
    end
    else begin	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:19:7
      if (w_en)	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        w_addr <= w_addr + 2'h1;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22, :43:30, :49:17
      if (r_en)	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:42:29
        r_addr <= r_addr + 2'h1;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:36:22, :44:30, :49:17
      if (_GEN_1 == 2'h1)	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:49:17, :58:{11,23}
        vaild_data <= vaild_data - 3'h1;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:57:28, :60:38
      else if (_GEN_1 == 2'h2)	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:49:17, :58:{11,23}
        vaild_data <= vaild_data + 3'h1;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:57:28, :60:38, :63:38
    end
    if (w_addr == 2'h0) begin	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22, :49:17
      if (w_en)	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        memory_0 <= io_fifo_wio_wdata;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17
      else	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        memory_0 <= _GEN_0;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17, :49:24
    end
    if (w_addr == 2'h1) begin	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22, :49:17
      if (w_en)	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        memory_1 <= io_fifo_wio_wdata;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17
      else	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        memory_1 <= _GEN_0;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17, :49:24
    end
    if (w_addr == 2'h2) begin	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22, :49:17
      if (w_en)	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        memory_2 <= io_fifo_wio_wdata;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17
      else	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        memory_2 <= _GEN_0;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17, :49:24
    end
    if (&w_addr) begin	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:35:22, :49:17
      if (w_en)	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        memory_3 <= io_fifo_wio_wdata;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17
      else	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:41:29
        memory_3 <= _GEN_0;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:46:17, :49:24
    end
  end // always @(posedge)
  assign io_fifo_rio_rdata = (|vaild_data) ? _GEN[r_addr] : io_fifo_wio_wdata;	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:19:7, :36:22, :49:24, :54:16, :57:28, :71:41
  assign io_fifo_rio_empty = ~(|vaild_data);	// src/main/scala/AXI2UI/fwft_sync_fifo.scala:19:7, :57:28, :71:41
endmodule

