// Generated by CIRCT firtool-1.62.0
module fwft_sync_fifo_5(
  input  clock,
         reset,
         io_fifo_wio_wen,
  output io_fifo_wio_full,
  input  io_fifo_rio_ren,
  output io_fifo_rio_empty
);

  reg  [4:0] vaild_data;
  wire       io_fifo_wio_full_0 = vaild_data == 5'h10;
  wire [1:0] _GEN =
    {io_fifo_wio_wen & (~io_fifo_wio_full_0 | io_fifo_rio_ren),
     io_fifo_rio_ren & ((|vaild_data) | io_fifo_wio_wen)};
  always @(posedge clock) begin
    if (reset)
      vaild_data <= 5'h0;
    else if (_GEN == 2'h1)
      vaild_data <= vaild_data - 5'h1;
    else if (_GEN == 2'h2)
      vaild_data <= vaild_data + 5'h1;
  end // always @(posedge)
  assign io_fifo_wio_full = io_fifo_wio_full_0;
  assign io_fifo_rio_empty = ~(|vaild_data);
endmodule

