// Generated by CIRCT firtool-1.62.0
module osmc_axi_read(
  input          clock,
                 reset,
  input  [35:0]  io_axi_ario_araddr,
  input  [7:0]   io_axi_ario_arlen,
  input  [2:0]   io_axi_ario_arsize,
  input  [1:0]   io_axi_ario_arburst,
  input  [3:0]   io_axi_ario_arqos,
  input          io_axi_ario_arvalid,
  output         io_axi_ario_arready,
  output [255:0] io_axi_rio_rdata,
  output         io_axi_rio_rlast,
                 io_axi_rio_rvalid,
  input          io_axi_rio_rready,
                 io_ui_ario_ready,
  output         io_ui_ario_valid,
  output [35:0]  io_ui_ario_bits_addr,
  output [9:0]   io_ui_ario_bits_token,
  input          io_ui_rio_valid,
  input  [511:0] io_ui_rio_bits_rdata,
  input  [9:0]   io_ui_rio_bits_rtoken,
                 io_token_inio_artoken,
  output         io_token_countio_token_aren,
                 io_ready_stall,
  input          io_rconsis,
  output [71:0]  io_consis_addr_io_addr_start_0,
                 io_consis_addr_io_addr_start_1,
                 io_consis_addr_io_addr_start_2,
                 io_consis_addr_io_addr_start_3,
                 io_consis_addr_io_addr_start_4,
                 io_consis_addr_io_addr_start_5,
                 io_consis_addr_io_addr_start_6,
                 io_consis_addr_io_addr_start_7,
                 io_consis_addr_io_addr_start_8,
                 io_consis_addr_io_addr_start_9,
                 io_consis_addr_io_addr_start_10,
                 io_consis_addr_io_addr_start_11,
                 io_consis_addr_io_addr_start_12,
                 io_consis_addr_io_addr_start_13,
                 io_consis_addr_io_addr_start_14,
                 io_consis_addr_io_addr_start_15,
                 io_consis_addr_io_addr_start_16,
                 io_consis_addr_io_addr_start_17,
                 io_consis_addr_io_addr_start_18,
                 io_consis_addr_io_addr_start_19,
                 io_consis_addr_io_addr_start_20,
                 io_consis_addr_io_addr_start_21,
                 io_consis_addr_io_addr_start_22,
                 io_consis_addr_io_addr_start_23,
                 io_consis_addr_io_addr_start_24,
                 io_consis_addr_io_addr_start_25,
                 io_consis_addr_io_addr_start_26,
                 io_consis_addr_io_addr_start_27,
                 io_consis_addr_io_addr_start_28,
                 io_consis_addr_io_addr_start_29,
                 io_consis_addr_io_addr_start_30,
                 io_consis_addr_io_addr_start_31,
                 io_consis_addr_io_addr_start_32,
                 io_consis_addr_io_addr_end_0,
                 io_consis_addr_io_addr_end_1,
                 io_consis_addr_io_addr_end_2,
                 io_consis_addr_io_addr_end_3,
                 io_consis_addr_io_addr_end_4,
                 io_consis_addr_io_addr_end_5,
                 io_consis_addr_io_addr_end_6,
                 io_consis_addr_io_addr_end_7,
                 io_consis_addr_io_addr_end_8,
                 io_consis_addr_io_addr_end_9,
                 io_consis_addr_io_addr_end_10,
                 io_consis_addr_io_addr_end_11,
                 io_consis_addr_io_addr_end_12,
                 io_consis_addr_io_addr_end_13,
                 io_consis_addr_io_addr_end_14,
                 io_consis_addr_io_addr_end_15,
                 io_consis_addr_io_addr_end_16,
                 io_consis_addr_io_addr_end_17,
                 io_consis_addr_io_addr_end_18,
                 io_consis_addr_io_addr_end_19,
                 io_consis_addr_io_addr_end_20,
                 io_consis_addr_io_addr_end_21,
                 io_consis_addr_io_addr_end_22,
                 io_consis_addr_io_addr_end_23,
                 io_consis_addr_io_addr_end_24,
                 io_consis_addr_io_addr_end_25,
                 io_consis_addr_io_addr_end_26,
                 io_consis_addr_io_addr_end_27,
                 io_consis_addr_io_addr_end_28,
                 io_consis_addr_io_addr_end_29,
                 io_consis_addr_io_addr_end_30,
                 io_consis_addr_io_addr_end_31,
                 io_consis_addr_io_addr_end_32,
  output [4:0]   io_consis_addr_io_axi_ptr,
                 io_consis_addr_io_ui_ptr,
  output [31:0]  io_ui_rdcmd_counter,
                 io_axi_rdcmd_counter,
                 io_ui_rdback_counter
);

  reg  [6:0]   rtoken_cnt;
  wire         _u_ui_read_cmd_io_ui_ario_valid;
  wire [35:0]  _u_ui_read_cmd_io_ui_ario_bits_addr;
  wire         _u_ui_read_cmd_io_fifol2_arrio_ren;
  wire [9:0]   _u_axi_r_cmdbuffer_io_token_fifo_rio_rdata;
  wire         _u_axi_r_cmdbuffer_io_token_fifo_wio_full;
  wire [10:0]  _u_axi_r_cmdbuffer_io_cmd_fifo_rio_rdata;
  wire         _u_axi_r_cmdbuffer_io_cmd_fifo_rio_empty;
  wire         _u_axi_r_cmdbuffer_io_cmd_fifo_wio_full;
  wire         _u_axi_rrob_io_cmd_fifo_rio_ren;
  wire [511:0] _u_axi_rrob_io_rdata_io_rdata;
  wire         _u_axi_rrob_io_rdata_io_rvalid;
  wire         _u_axi_r_fifol1_io_fifo_wio_full;
  wire [256:0] _u_axi_r_fifol1_io_fifo_rio_rdata;
  wire         _u_axi_r_fifol1_io_fifo_rio_empty;
  wire         _u_axi_ar_fifol2_io_fifo_wio_full;
  wire [45:0]  _u_axi_ar_fifol2_io_fifo_rio_rdata;
  wire         _u_axi_ar_fifol2_io_fifo_rio_empty;
  wire         _u_axi_ar_fifol1_io_fifo_wio_full;
  wire [53:0]  _u_axi_ar_fifol1_io_fifo_rio_rdata;
  wire         _u_axi_ar_fifol1_io_fifo_rio_empty;
  wire         _u_axi_read_burst_clip_io_fifol1_arrio_ren;
  wire         _u_axi_read_burst_clip_io_fifol2_arwio_wen;
  wire [45:0]  _u_axi_read_burst_clip_io_fifol2_arwio_wdata;
  wire         _u_axi_read_burst_clip_io_fifol1_rwio_wen;
  wire [256:0] _u_axi_read_burst_clip_io_fifol1_rwio_wdata;
  wire         _u_axi_read_burst_clip_io_cmd_fifo_wio_wen;
  wire [10:0]  _u_axi_read_burst_clip_io_cmd_fifo_wio_wdata;
  wire         _u_axi_read_burst_clip_io_cmd_fifo_rio_ren;
  wire         _u_axi_read_burst_clip_io_token_fifo_wio_wen;
  wire [9:0]   _u_axi_read_burst_clip_io_token_fifo_wio_wdata;
  wire         _u_axi_read_burst_clip_io_rrob_io_rready;
  reg  [35:0]  addr0;
  reg  [7:0]   len;
  reg  [2:0]   size;
  reg  [1:0]   burst;
  reg  [3:0]   qos;
  reg          avalid;
  reg          aready;
  reg          cmd_end0;
  reg          cmd_hold;
  reg  [31:0]  axi_rdcmd_cnt;
  reg  [31:0]  ui_rdback_cnt;
  wire         _u_axi_ar_fifol1_io_fifo_wio_wen_T = avalid & aready;
  wire         _u_axi_ar_fifol1_io_fifo_wio_wen_T_5 =
    (_u_axi_ar_fifol1_io_fifo_wio_wen_T | cmd_hold) & ~_u_axi_ar_fifol1_io_fifo_wio_full
    & ~io_rconsis;
  reg          rdata_counter;
  wire         _u_axi_r_fifol1_io_fifo_rio_ren_T =
    io_axi_rio_rready & ~_u_axi_r_fifol1_io_fifo_rio_empty;
  wire         io_axi_rio_rlast_0 =
    rdata_counter & io_axi_rio_rready & ~_u_axi_r_fifol1_io_fifo_rio_empty;
  wire         io_axi_ario_arready_0 =
    ~_u_axi_ar_fifol1_io_fifo_wio_full & ~io_rconsis & ~cmd_hold;
  wire [1:0]   _GEN =
    {_u_ui_read_cmd_io_ui_ario_valid & io_ui_ario_ready, _u_axi_rrob_io_cmd_fifo_rio_ren};
  wire         cmd_en = io_axi_ario_arvalid & io_axi_ario_arready_0;
  always @(posedge clock) begin
    if (reset) begin
      addr0 <= 36'h0;
      len <= 8'h0;
      size <= 3'h0;
      burst <= 2'h0;
      qos <= 4'h0;
      cmd_hold <= 1'h0;
      axi_rdcmd_cnt <= 32'h0;
      ui_rdback_cnt <= 32'h0;
      rdata_counter <= 1'h0;
      rtoken_cnt <= 7'h0;
    end
    else begin
      if (cmd_en) begin
        addr0 <= io_axi_ario_araddr;
        len <= io_axi_ario_arlen;
        size <= io_axi_ario_arsize;
        burst <= io_axi_ario_arburst;
        qos <= io_axi_ario_arqos;
      end
      else if (_u_axi_ar_fifol1_io_fifo_wio_wen_T_5) begin
        addr0 <= 36'h0;
        len <= 8'h0;
        size <= 3'h0;
        burst <= 2'h0;
        qos <= 4'h0;
      end
      cmd_hold <=
        cmd_end0 & _u_axi_ar_fifol1_io_fifo_wio_full | io_rconsis & cmd_end0
        | ~_u_axi_ar_fifol1_io_fifo_wio_wen_T_5 & cmd_hold;
      if (_u_axi_ar_fifol1_io_fifo_wio_wen_T)
        axi_rdcmd_cnt <= axi_rdcmd_cnt + 32'h1;
      if (io_axi_rio_rlast_0 & ~_u_axi_r_fifol1_io_fifo_rio_empty & io_axi_rio_rready)
        ui_rdback_cnt <= ui_rdback_cnt + 32'h1;
      if (_u_axi_r_fifol1_io_fifo_rio_ren_T)
        rdata_counter <= rdata_counter - 1'h1;
      if (_GEN == 2'h1)
        rtoken_cnt <= rtoken_cnt - 7'h1;
      else if (_GEN == 2'h2)
        rtoken_cnt <= rtoken_cnt + 7'h1;
    end
    avalid <= io_axi_ario_arvalid;
    aready <= io_axi_ario_arready_0;
    cmd_end0 <= cmd_en;
  end // always @(posedge)
  osmc_axi_read_burst_clip u_axi_read_burst_clip (
    .clock                       (clock),
    .reset                       (reset),
    .io_fifol1_arrio_ren         (_u_axi_read_burst_clip_io_fifol1_arrio_ren),
    .io_fifol1_arrio_rdata       (_u_axi_ar_fifol1_io_fifo_rio_rdata),
    .io_fifol1_arrio_empty       (_u_axi_ar_fifol1_io_fifo_rio_empty),
    .io_fifol2_arwio_wen         (_u_axi_read_burst_clip_io_fifol2_arwio_wen),
    .io_fifol2_arwio_wdata       (_u_axi_read_burst_clip_io_fifol2_arwio_wdata),
    .io_fifol2_arwio_full        (_u_axi_ar_fifol2_io_fifo_wio_full),
    .io_fifol1_rwio_wen          (_u_axi_read_burst_clip_io_fifol1_rwio_wen),
    .io_fifol1_rwio_wdata        (_u_axi_read_burst_clip_io_fifol1_rwio_wdata),
    .io_fifol1_rwio_full         (_u_axi_r_fifol1_io_fifo_wio_full),
    .io_token_inio_artoken       (io_token_inio_artoken),
    .io_token_countio_token_aren (io_token_countio_token_aren),
    .io_cmd_fifo_wio_wen         (_u_axi_read_burst_clip_io_cmd_fifo_wio_wen),
    .io_cmd_fifo_wio_wdata       (_u_axi_read_burst_clip_io_cmd_fifo_wio_wdata),
    .io_cmd_fifo_wio_full        (_u_axi_r_cmdbuffer_io_cmd_fifo_wio_full),
    .io_cmd_fifo_rio_ren         (_u_axi_read_burst_clip_io_cmd_fifo_rio_ren),
    .io_cmd_fifo_rio_rdata       (_u_axi_r_cmdbuffer_io_cmd_fifo_rio_rdata),
    .io_cmd_fifo_rio_empty       (_u_axi_r_cmdbuffer_io_cmd_fifo_rio_empty),
    .io_token_fifo_wio_wen       (_u_axi_read_burst_clip_io_token_fifo_wio_wen),
    .io_token_fifo_wio_wdata     (_u_axi_read_burst_clip_io_token_fifo_wio_wdata),
    .io_token_fifo_wio_full      (_u_axi_r_cmdbuffer_io_token_fifo_wio_full),
    .io_rrob_io_rdata            (_u_axi_rrob_io_rdata_io_rdata),
    .io_rrob_io_rvalid           (_u_axi_rrob_io_rdata_io_rvalid),
    .io_rrob_io_rready           (_u_axi_read_burst_clip_io_rrob_io_rready)
  );
  fwft_sync_fifo_6 u_axi_ar_fifol1 (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (_u_axi_ar_fifol1_io_fifo_wio_wen_T_5),
    .io_fifo_wio_wdata ({1'h0, addr0, burst, len, size, qos}),
    .io_fifo_wio_full  (_u_axi_ar_fifol1_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_axi_read_burst_clip_io_fifol1_arrio_ren),
    .io_fifo_rio_rdata (_u_axi_ar_fifol1_io_fifo_rio_rdata),
    .io_fifo_rio_empty (_u_axi_ar_fifol1_io_fifo_rio_empty)
  );
  fwft_sync_fifo_1 u_axi_ar_fifol2 (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (_u_axi_read_burst_clip_io_fifol2_arwio_wen),
    .io_fifo_wio_wdata (_u_axi_read_burst_clip_io_fifol2_arwio_wdata),
    .io_fifo_wio_full  (_u_axi_ar_fifol2_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_ui_read_cmd_io_fifol2_arrio_ren),
    .io_fifo_rio_rdata (_u_axi_ar_fifol2_io_fifo_rio_rdata),
    .io_fifo_rio_empty (_u_axi_ar_fifol2_io_fifo_rio_empty)
  );
  fwft_sync_fifo_8 u_axi_r_fifol1 (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (_u_axi_read_burst_clip_io_fifol1_rwio_wen),
    .io_fifo_wio_wdata (_u_axi_read_burst_clip_io_fifol1_rwio_wdata),
    .io_fifo_wio_full  (_u_axi_r_fifol1_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_axi_r_fifol1_io_fifo_rio_ren_T),
    .io_fifo_rio_rdata (_u_axi_r_fifol1_io_fifo_rio_rdata),
    .io_fifo_rio_empty (_u_axi_r_fifol1_io_fifo_rio_empty)
  );
  osmc_axi_read_rob u_axi_rrob (
    .clock                 (clock),
    .reset                 (reset),
    .io_ui_rio_valid       (io_ui_rio_valid),
    .io_ui_rio_bits_rdata  (io_ui_rio_bits_rdata),
    .io_ui_rio_bits_rtoken (io_ui_rio_bits_rtoken),
    .io_cmd_fifo_rio_ren   (_u_axi_rrob_io_cmd_fifo_rio_ren),
    .io_cmd_fifo_rio_rdata (_u_axi_r_cmdbuffer_io_token_fifo_rio_rdata),
    .io_rdata_io_rdata     (_u_axi_rrob_io_rdata_io_rdata),
    .io_rdata_io_rvalid    (_u_axi_rrob_io_rdata_io_rvalid),
    .io_rdata_io_rready    (_u_axi_read_burst_clip_io_rrob_io_rready)
  );
  osmc_axi_read_cmd_buffer u_axi_r_cmdbuffer (
    .clock                   (clock),
    .reset                   (reset),
    .io_token_fifo_rio_ren   (_u_axi_rrob_io_cmd_fifo_rio_ren),
    .io_token_fifo_rio_rdata (_u_axi_r_cmdbuffer_io_token_fifo_rio_rdata),
    .io_token_fifo_wio_wen   (_u_axi_read_burst_clip_io_token_fifo_wio_wen),
    .io_token_fifo_wio_wdata (_u_axi_read_burst_clip_io_token_fifo_wio_wdata),
    .io_token_fifo_wio_full  (_u_axi_r_cmdbuffer_io_token_fifo_wio_full),
    .io_cmd_fifo_rio_ren     (_u_axi_read_burst_clip_io_cmd_fifo_rio_ren),
    .io_cmd_fifo_rio_rdata   (_u_axi_r_cmdbuffer_io_cmd_fifo_rio_rdata),
    .io_cmd_fifo_rio_empty   (_u_axi_r_cmdbuffer_io_cmd_fifo_rio_empty),
    .io_cmd_fifo_wio_wen     (_u_axi_read_burst_clip_io_cmd_fifo_wio_wen),
    .io_cmd_fifo_wio_wdata   (_u_axi_read_burst_clip_io_cmd_fifo_wio_wdata),
    .io_cmd_fifo_wio_full    (_u_axi_r_cmdbuffer_io_cmd_fifo_wio_full)
  );
  osmc_ui_read_cmd u_ui_read_cmd (
    .clock                 (clock),
    .reset                 (reset),
    .io_ui_ario_ready      (io_ui_ario_ready),
    .io_ui_ario_valid      (_u_ui_read_cmd_io_ui_ario_valid),
    .io_ui_ario_bits_addr  (_u_ui_read_cmd_io_ui_ario_bits_addr),
    .io_ui_ario_bits_token (io_ui_ario_bits_token),
    .io_fifol2_arrio_ren   (_u_ui_read_cmd_io_fifol2_arrio_ren),
    .io_fifol2_arrio_rdata (_u_axi_ar_fifol2_io_fifo_rio_rdata),
    .io_fifol2_arrio_empty (_u_axi_ar_fifol2_io_fifo_rio_empty),
    .io_ready_stall        (&rtoken_cnt),
    .io_ui_rdcmd_counter   (io_ui_rdcmd_counter)
  );
  osmc_axi_consis_table r_axi_consis_table (
    .clock                           (clock),
    .reset                           (reset),
    .io_axi_aio_aaddr                (io_axi_ario_araddr),
    .io_axi_aio_alen                 (io_axi_ario_arlen),
    .io_axi_aio_asize                (io_axi_ario_arsize),
    .io_axi_aio_avalid               (io_axi_ario_arvalid),
    .io_axi_aio_aready               (io_axi_ario_arready_0),
    .io_ui_aio_addr                  (_u_ui_read_cmd_io_ui_ario_bits_addr),
    .io_ui_hsio_ready                (io_ui_ario_ready),
    .io_ui_hsio_valid                (_u_ui_read_cmd_io_ui_ario_valid),
    .io_consis_addr_io_addr_start_0  (io_consis_addr_io_addr_start_0),
    .io_consis_addr_io_addr_start_1  (io_consis_addr_io_addr_start_1),
    .io_consis_addr_io_addr_start_2  (io_consis_addr_io_addr_start_2),
    .io_consis_addr_io_addr_start_3  (io_consis_addr_io_addr_start_3),
    .io_consis_addr_io_addr_start_4  (io_consis_addr_io_addr_start_4),
    .io_consis_addr_io_addr_start_5  (io_consis_addr_io_addr_start_5),
    .io_consis_addr_io_addr_start_6  (io_consis_addr_io_addr_start_6),
    .io_consis_addr_io_addr_start_7  (io_consis_addr_io_addr_start_7),
    .io_consis_addr_io_addr_start_8  (io_consis_addr_io_addr_start_8),
    .io_consis_addr_io_addr_start_9  (io_consis_addr_io_addr_start_9),
    .io_consis_addr_io_addr_start_10 (io_consis_addr_io_addr_start_10),
    .io_consis_addr_io_addr_start_11 (io_consis_addr_io_addr_start_11),
    .io_consis_addr_io_addr_start_12 (io_consis_addr_io_addr_start_12),
    .io_consis_addr_io_addr_start_13 (io_consis_addr_io_addr_start_13),
    .io_consis_addr_io_addr_start_14 (io_consis_addr_io_addr_start_14),
    .io_consis_addr_io_addr_start_15 (io_consis_addr_io_addr_start_15),
    .io_consis_addr_io_addr_start_16 (io_consis_addr_io_addr_start_16),
    .io_consis_addr_io_addr_start_17 (io_consis_addr_io_addr_start_17),
    .io_consis_addr_io_addr_start_18 (io_consis_addr_io_addr_start_18),
    .io_consis_addr_io_addr_start_19 (io_consis_addr_io_addr_start_19),
    .io_consis_addr_io_addr_start_20 (io_consis_addr_io_addr_start_20),
    .io_consis_addr_io_addr_start_21 (io_consis_addr_io_addr_start_21),
    .io_consis_addr_io_addr_start_22 (io_consis_addr_io_addr_start_22),
    .io_consis_addr_io_addr_start_23 (io_consis_addr_io_addr_start_23),
    .io_consis_addr_io_addr_start_24 (io_consis_addr_io_addr_start_24),
    .io_consis_addr_io_addr_start_25 (io_consis_addr_io_addr_start_25),
    .io_consis_addr_io_addr_start_26 (io_consis_addr_io_addr_start_26),
    .io_consis_addr_io_addr_start_27 (io_consis_addr_io_addr_start_27),
    .io_consis_addr_io_addr_start_28 (io_consis_addr_io_addr_start_28),
    .io_consis_addr_io_addr_start_29 (io_consis_addr_io_addr_start_29),
    .io_consis_addr_io_addr_start_30 (io_consis_addr_io_addr_start_30),
    .io_consis_addr_io_addr_start_31 (io_consis_addr_io_addr_start_31),
    .io_consis_addr_io_addr_start_32 (io_consis_addr_io_addr_start_32),
    .io_consis_addr_io_addr_end_0    (io_consis_addr_io_addr_end_0),
    .io_consis_addr_io_addr_end_1    (io_consis_addr_io_addr_end_1),
    .io_consis_addr_io_addr_end_2    (io_consis_addr_io_addr_end_2),
    .io_consis_addr_io_addr_end_3    (io_consis_addr_io_addr_end_3),
    .io_consis_addr_io_addr_end_4    (io_consis_addr_io_addr_end_4),
    .io_consis_addr_io_addr_end_5    (io_consis_addr_io_addr_end_5),
    .io_consis_addr_io_addr_end_6    (io_consis_addr_io_addr_end_6),
    .io_consis_addr_io_addr_end_7    (io_consis_addr_io_addr_end_7),
    .io_consis_addr_io_addr_end_8    (io_consis_addr_io_addr_end_8),
    .io_consis_addr_io_addr_end_9    (io_consis_addr_io_addr_end_9),
    .io_consis_addr_io_addr_end_10   (io_consis_addr_io_addr_end_10),
    .io_consis_addr_io_addr_end_11   (io_consis_addr_io_addr_end_11),
    .io_consis_addr_io_addr_end_12   (io_consis_addr_io_addr_end_12),
    .io_consis_addr_io_addr_end_13   (io_consis_addr_io_addr_end_13),
    .io_consis_addr_io_addr_end_14   (io_consis_addr_io_addr_end_14),
    .io_consis_addr_io_addr_end_15   (io_consis_addr_io_addr_end_15),
    .io_consis_addr_io_addr_end_16   (io_consis_addr_io_addr_end_16),
    .io_consis_addr_io_addr_end_17   (io_consis_addr_io_addr_end_17),
    .io_consis_addr_io_addr_end_18   (io_consis_addr_io_addr_end_18),
    .io_consis_addr_io_addr_end_19   (io_consis_addr_io_addr_end_19),
    .io_consis_addr_io_addr_end_20   (io_consis_addr_io_addr_end_20),
    .io_consis_addr_io_addr_end_21   (io_consis_addr_io_addr_end_21),
    .io_consis_addr_io_addr_end_22   (io_consis_addr_io_addr_end_22),
    .io_consis_addr_io_addr_end_23   (io_consis_addr_io_addr_end_23),
    .io_consis_addr_io_addr_end_24   (io_consis_addr_io_addr_end_24),
    .io_consis_addr_io_addr_end_25   (io_consis_addr_io_addr_end_25),
    .io_consis_addr_io_addr_end_26   (io_consis_addr_io_addr_end_26),
    .io_consis_addr_io_addr_end_27   (io_consis_addr_io_addr_end_27),
    .io_consis_addr_io_addr_end_28   (io_consis_addr_io_addr_end_28),
    .io_consis_addr_io_addr_end_29   (io_consis_addr_io_addr_end_29),
    .io_consis_addr_io_addr_end_30   (io_consis_addr_io_addr_end_30),
    .io_consis_addr_io_addr_end_31   (io_consis_addr_io_addr_end_31),
    .io_consis_addr_io_addr_end_32   (io_consis_addr_io_addr_end_32),
    .io_consis_addr_io_axi_ptr       (io_consis_addr_io_axi_ptr),
    .io_consis_addr_io_ui_ptr        (io_consis_addr_io_ui_ptr)
  );
  assign io_axi_ario_arready = io_axi_ario_arready_0;
  assign io_axi_rio_rdata = _u_axi_r_fifol1_io_fifo_rio_rdata[255:0];
  assign io_axi_rio_rlast = io_axi_rio_rlast_0;
  assign io_axi_rio_rvalid = ~_u_axi_r_fifol1_io_fifo_rio_empty;
  assign io_ui_ario_valid = _u_ui_read_cmd_io_ui_ario_valid;
  assign io_ui_ario_bits_addr = _u_ui_read_cmd_io_ui_ario_bits_addr;
  assign io_ready_stall = &rtoken_cnt;
  assign io_axi_rdcmd_counter = axi_rdcmd_cnt;
  assign io_ui_rdback_counter = ui_rdback_cnt;
endmodule

