// Generated by CIRCT firtool-1.62.0
module osmc_axi_top(	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7
  input          clock,	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7
                 reset,	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7
  input  [7:0]   io_awio_awid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [35:0]  io_awio_awaddr,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [7:0]   io_awio_awlen,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [2:0]   io_awio_awsize,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [1:0]   io_awio_awburst,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_awio_awuser,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [3:0]   io_awio_awqos,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_awio_awvalid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_awio_awready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_wio_wuser,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [255:0] io_wio_wdata,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [31:0]  io_wio_wstrb,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_wio_wlast,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_wio_wvalid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_wio_wready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [7:0]   io_bio_bid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [1:0]   io_bio_bresp,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_bio_buser,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_bio_bvalid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_bio_bready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [7:0]   io_ario_arid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [35:0]  io_ario_araddr,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [7:0]   io_ario_arlen,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [2:0]   io_ario_arsize,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [1:0]   io_ario_arburst,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_ario_aruser,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [3:0]   io_ario_arqos,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_ario_arvalid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_ario_arready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [7:0]   io_rio_rid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_rio_ruser,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [255:0] io_rio_rdata,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [1:0]   io_rio_rresp,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_rio_rlast,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_rio_rvalid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_rio_rready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_ui_awio_ready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_ui_awio_valid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [35:0]  io_ui_awio_bits_addr,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [9:0]   io_ui_awio_bits_token,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_ui_awio_bits_pri,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_ui_wio_ready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_ui_wio_valid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [511:0] io_ui_wio_bits_wdata,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [63:0]  io_ui_wio_bits_wstrb,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_ui_ario_ready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_ui_ario_valid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [35:0]  io_ui_ario_bits_addr,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [9:0]   io_ui_ario_bits_token,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_ui_ario_bits_pri,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_ui_rio_ready,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_ui_rio_valid,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [511:0] io_ui_rio_bits_rdata,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input  [9:0]   io_ui_rio_bits_rtoken,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [31:0]  io_a2uregio_axiRdCmdCnt,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_a2uregio_axiWrCmdCnt,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_a2uregio_uiRdCmdCnt,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_a2uregio_uiWrCmdCnt,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
                 io_a2uregio_uiRbCmdCnt,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output         io_a2uregio_readyStall,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  output [7:0]   io_a2uregio_tokenCnt,	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
  input          io_apb_config_done	// src/main/scala/AXI2UI/osmc_axi_top.scala:36:12
);

  wire        _u_axi_consis_io_consis_io_wconsis;	// src/main/scala/AXI2UI/osmc_axi_top.scala:75:26
  wire        _u_axi_consis_io_consis_io_rconsis;	// src/main/scala/AXI2UI/osmc_axi_top.scala:75:26
  wire [9:0]  _u_axi_token_io_token_io_awtoken;	// src/main/scala/AXI2UI/osmc_axi_top.scala:66:25
  wire [9:0]  _u_axi_token_io_token_io_artoken;	// src/main/scala/AXI2UI/osmc_axi_top.scala:66:25
  wire        _u_axi_read_io_token_countio_token_aren;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire        _u_axi_read_io_ready_stall;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_1;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_2;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_3;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_4;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_5;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_6;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_7;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_8;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_9;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_10;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_11;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_12;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_13;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_14;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_15;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_16;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_17;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_18;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_19;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_20;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_21;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_22;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_23;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_24;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_25;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_26;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_27;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_28;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_29;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_30;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_31;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_32;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_1;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_2;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_3;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_4;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_5;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_6;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_7;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_8;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_9;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_10;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_11;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_12;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_13;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_14;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_15;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_16;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_17;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_18;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_19;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_20;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_21;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_22;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_23;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_24;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_25;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_26;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_27;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_28;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_29;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_30;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_31;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_32;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [4:0]  _u_axi_read_io_consis_addr_io_axi_ptr;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire [4:0]  _u_axi_read_io_consis_addr_io_ui_ptr;	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  wire        _u_axi_write_io_token_countio_token_awen;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_1;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_2;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_3;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_4;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_5;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_6;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_7;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_8;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_9;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_10;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_11;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_12;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_13;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_14;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_15;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_16;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_17;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_18;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_19;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_20;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_21;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_22;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_23;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_24;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_25;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_26;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_27;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_28;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_29;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_30;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_31;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_32;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_1;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_2;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_3;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_4;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_5;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_6;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_7;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_8;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_9;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_10;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_11;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_12;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_13;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_14;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_15;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_16;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_17;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_18;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_19;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_20;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_21;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_22;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_23;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_24;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_25;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_26;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_27;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_28;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_29;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_30;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_31;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_32;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [4:0]  _u_axi_write_io_consis_addr_io_axi_ptr;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  wire [4:0]  _u_axi_write_io_consis_addr_io_ui_ptr;	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
  osmc_axi_write u_axi_write (	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .clock                           (clock),
    .reset                           (reset),
    .io_axi_awio_awid                (io_awio_awid),
    .io_axi_awio_awaddr              (io_awio_awaddr),
    .io_axi_awio_awlen               (io_awio_awlen),
    .io_axi_awio_awsize              (io_awio_awsize),
    .io_axi_awio_awburst             (io_awio_awburst),
    .io_axi_awio_awuser              (io_awio_awuser),
    .io_axi_awio_awqos               (io_awio_awqos),
    .io_axi_awio_awvalid             (io_awio_awvalid),
    .io_axi_awio_awready             (io_awio_awready),
    .io_axi_wio_wdata                (io_wio_wdata),
    .io_axi_wio_wstrb                (io_wio_wstrb),
    .io_axi_wio_wlast                (io_wio_wlast),
    .io_axi_wio_wvalid               (io_wio_wvalid),
    .io_axi_wio_wready               (io_wio_wready),
    .io_axi_bio_bid                  (io_bio_bid),
    .io_axi_bio_buser                (io_bio_buser),
    .io_axi_bio_bvalid               (io_bio_bvalid),
    .io_axi_bio_bready               (io_bio_bready),
    .io_ui_awio_ready                (io_ui_awio_ready),
    .io_ui_awio_valid                (io_ui_awio_valid),
    .io_ui_awio_bits_addr            (io_ui_awio_bits_addr),
    .io_ui_awio_bits_token           (io_ui_awio_bits_token),
    .io_ui_wio_ready                 (io_ui_wio_ready),
    .io_ui_wio_valid                 (io_ui_wio_valid),
    .io_ui_wio_bits_wdata            (io_ui_wio_bits_wdata),
    .io_ui_wio_bits_wstrb            (io_ui_wio_bits_wstrb),
    .io_token_inio_awtoken           (_u_axi_token_io_token_io_awtoken),	// src/main/scala/AXI2UI/osmc_axi_top.scala:66:25
    .io_token_countio_token_awen     (_u_axi_write_io_token_countio_token_awen),
    .io_ready_stall                  (_u_axi_read_io_ready_stall),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_wconsis                      (_u_axi_consis_io_consis_io_wconsis),	// src/main/scala/AXI2UI/osmc_axi_top.scala:75:26
    .io_consis_addr_io_addr_start_0  (_u_axi_write_io_consis_addr_io_addr_start_0),
    .io_consis_addr_io_addr_start_1  (_u_axi_write_io_consis_addr_io_addr_start_1),
    .io_consis_addr_io_addr_start_2  (_u_axi_write_io_consis_addr_io_addr_start_2),
    .io_consis_addr_io_addr_start_3  (_u_axi_write_io_consis_addr_io_addr_start_3),
    .io_consis_addr_io_addr_start_4  (_u_axi_write_io_consis_addr_io_addr_start_4),
    .io_consis_addr_io_addr_start_5  (_u_axi_write_io_consis_addr_io_addr_start_5),
    .io_consis_addr_io_addr_start_6  (_u_axi_write_io_consis_addr_io_addr_start_6),
    .io_consis_addr_io_addr_start_7  (_u_axi_write_io_consis_addr_io_addr_start_7),
    .io_consis_addr_io_addr_start_8  (_u_axi_write_io_consis_addr_io_addr_start_8),
    .io_consis_addr_io_addr_start_9  (_u_axi_write_io_consis_addr_io_addr_start_9),
    .io_consis_addr_io_addr_start_10 (_u_axi_write_io_consis_addr_io_addr_start_10),
    .io_consis_addr_io_addr_start_11 (_u_axi_write_io_consis_addr_io_addr_start_11),
    .io_consis_addr_io_addr_start_12 (_u_axi_write_io_consis_addr_io_addr_start_12),
    .io_consis_addr_io_addr_start_13 (_u_axi_write_io_consis_addr_io_addr_start_13),
    .io_consis_addr_io_addr_start_14 (_u_axi_write_io_consis_addr_io_addr_start_14),
    .io_consis_addr_io_addr_start_15 (_u_axi_write_io_consis_addr_io_addr_start_15),
    .io_consis_addr_io_addr_start_16 (_u_axi_write_io_consis_addr_io_addr_start_16),
    .io_consis_addr_io_addr_start_17 (_u_axi_write_io_consis_addr_io_addr_start_17),
    .io_consis_addr_io_addr_start_18 (_u_axi_write_io_consis_addr_io_addr_start_18),
    .io_consis_addr_io_addr_start_19 (_u_axi_write_io_consis_addr_io_addr_start_19),
    .io_consis_addr_io_addr_start_20 (_u_axi_write_io_consis_addr_io_addr_start_20),
    .io_consis_addr_io_addr_start_21 (_u_axi_write_io_consis_addr_io_addr_start_21),
    .io_consis_addr_io_addr_start_22 (_u_axi_write_io_consis_addr_io_addr_start_22),
    .io_consis_addr_io_addr_start_23 (_u_axi_write_io_consis_addr_io_addr_start_23),
    .io_consis_addr_io_addr_start_24 (_u_axi_write_io_consis_addr_io_addr_start_24),
    .io_consis_addr_io_addr_start_25 (_u_axi_write_io_consis_addr_io_addr_start_25),
    .io_consis_addr_io_addr_start_26 (_u_axi_write_io_consis_addr_io_addr_start_26),
    .io_consis_addr_io_addr_start_27 (_u_axi_write_io_consis_addr_io_addr_start_27),
    .io_consis_addr_io_addr_start_28 (_u_axi_write_io_consis_addr_io_addr_start_28),
    .io_consis_addr_io_addr_start_29 (_u_axi_write_io_consis_addr_io_addr_start_29),
    .io_consis_addr_io_addr_start_30 (_u_axi_write_io_consis_addr_io_addr_start_30),
    .io_consis_addr_io_addr_start_31 (_u_axi_write_io_consis_addr_io_addr_start_31),
    .io_consis_addr_io_addr_start_32 (_u_axi_write_io_consis_addr_io_addr_start_32),
    .io_consis_addr_io_addr_end_0    (_u_axi_write_io_consis_addr_io_addr_end_0),
    .io_consis_addr_io_addr_end_1    (_u_axi_write_io_consis_addr_io_addr_end_1),
    .io_consis_addr_io_addr_end_2    (_u_axi_write_io_consis_addr_io_addr_end_2),
    .io_consis_addr_io_addr_end_3    (_u_axi_write_io_consis_addr_io_addr_end_3),
    .io_consis_addr_io_addr_end_4    (_u_axi_write_io_consis_addr_io_addr_end_4),
    .io_consis_addr_io_addr_end_5    (_u_axi_write_io_consis_addr_io_addr_end_5),
    .io_consis_addr_io_addr_end_6    (_u_axi_write_io_consis_addr_io_addr_end_6),
    .io_consis_addr_io_addr_end_7    (_u_axi_write_io_consis_addr_io_addr_end_7),
    .io_consis_addr_io_addr_end_8    (_u_axi_write_io_consis_addr_io_addr_end_8),
    .io_consis_addr_io_addr_end_9    (_u_axi_write_io_consis_addr_io_addr_end_9),
    .io_consis_addr_io_addr_end_10   (_u_axi_write_io_consis_addr_io_addr_end_10),
    .io_consis_addr_io_addr_end_11   (_u_axi_write_io_consis_addr_io_addr_end_11),
    .io_consis_addr_io_addr_end_12   (_u_axi_write_io_consis_addr_io_addr_end_12),
    .io_consis_addr_io_addr_end_13   (_u_axi_write_io_consis_addr_io_addr_end_13),
    .io_consis_addr_io_addr_end_14   (_u_axi_write_io_consis_addr_io_addr_end_14),
    .io_consis_addr_io_addr_end_15   (_u_axi_write_io_consis_addr_io_addr_end_15),
    .io_consis_addr_io_addr_end_16   (_u_axi_write_io_consis_addr_io_addr_end_16),
    .io_consis_addr_io_addr_end_17   (_u_axi_write_io_consis_addr_io_addr_end_17),
    .io_consis_addr_io_addr_end_18   (_u_axi_write_io_consis_addr_io_addr_end_18),
    .io_consis_addr_io_addr_end_19   (_u_axi_write_io_consis_addr_io_addr_end_19),
    .io_consis_addr_io_addr_end_20   (_u_axi_write_io_consis_addr_io_addr_end_20),
    .io_consis_addr_io_addr_end_21   (_u_axi_write_io_consis_addr_io_addr_end_21),
    .io_consis_addr_io_addr_end_22   (_u_axi_write_io_consis_addr_io_addr_end_22),
    .io_consis_addr_io_addr_end_23   (_u_axi_write_io_consis_addr_io_addr_end_23),
    .io_consis_addr_io_addr_end_24   (_u_axi_write_io_consis_addr_io_addr_end_24),
    .io_consis_addr_io_addr_end_25   (_u_axi_write_io_consis_addr_io_addr_end_25),
    .io_consis_addr_io_addr_end_26   (_u_axi_write_io_consis_addr_io_addr_end_26),
    .io_consis_addr_io_addr_end_27   (_u_axi_write_io_consis_addr_io_addr_end_27),
    .io_consis_addr_io_addr_end_28   (_u_axi_write_io_consis_addr_io_addr_end_28),
    .io_consis_addr_io_addr_end_29   (_u_axi_write_io_consis_addr_io_addr_end_29),
    .io_consis_addr_io_addr_end_30   (_u_axi_write_io_consis_addr_io_addr_end_30),
    .io_consis_addr_io_addr_end_31   (_u_axi_write_io_consis_addr_io_addr_end_31),
    .io_consis_addr_io_addr_end_32   (_u_axi_write_io_consis_addr_io_addr_end_32),
    .io_consis_addr_io_axi_ptr       (_u_axi_write_io_consis_addr_io_axi_ptr),
    .io_consis_addr_io_ui_ptr        (_u_axi_write_io_consis_addr_io_ui_ptr),
    .io_ui_wtcmd_counter             (io_a2uregio_uiWrCmdCnt),
    .io_axi_wtcmd_counter            (io_a2uregio_axiWrCmdCnt),
    .io_apb_config_done              (io_apb_config_done)
  );
  osmc_axi_read u_axi_read (	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .clock                           (clock),
    .reset                           (reset),
    .io_axi_ario_arid                (io_ario_arid),
    .io_axi_ario_araddr              (io_ario_araddr),
    .io_axi_ario_arlen               (io_ario_arlen),
    .io_axi_ario_arsize              (io_ario_arsize),
    .io_axi_ario_arburst             (io_ario_arburst),
    .io_axi_ario_aruser              (io_ario_aruser),
    .io_axi_ario_arqos               (io_ario_arqos),
    .io_axi_ario_arvalid             (io_ario_arvalid),
    .io_axi_ario_arready             (io_ario_arready),
    .io_axi_rio_rid                  (io_rio_rid),
    .io_axi_rio_ruser                (io_rio_ruser),
    .io_axi_rio_rdata                (io_rio_rdata),
    .io_axi_rio_rlast                (io_rio_rlast),
    .io_axi_rio_rvalid               (io_rio_rvalid),
    .io_axi_rio_rready               (io_rio_rready),
    .io_ui_ario_ready                (io_ui_ario_ready),
    .io_ui_ario_valid                (io_ui_ario_valid),
    .io_ui_ario_bits_addr            (io_ui_ario_bits_addr),
    .io_ui_ario_bits_token           (io_ui_ario_bits_token),
    .io_ui_rio_valid                 (io_ui_rio_valid),
    .io_ui_rio_bits_rdata            (io_ui_rio_bits_rdata),
    .io_ui_rio_bits_rtoken           (io_ui_rio_bits_rtoken),
    .io_token_inio_artoken           (_u_axi_token_io_token_io_artoken),	// src/main/scala/AXI2UI/osmc_axi_top.scala:66:25
    .io_token_countio_token_aren     (_u_axi_read_io_token_countio_token_aren),
    .io_ready_stall                  (_u_axi_read_io_ready_stall),
    .io_rconsis                      (_u_axi_consis_io_consis_io_rconsis),	// src/main/scala/AXI2UI/osmc_axi_top.scala:75:26
    .io_consis_addr_io_addr_start_0  (_u_axi_read_io_consis_addr_io_addr_start_0),
    .io_consis_addr_io_addr_start_1  (_u_axi_read_io_consis_addr_io_addr_start_1),
    .io_consis_addr_io_addr_start_2  (_u_axi_read_io_consis_addr_io_addr_start_2),
    .io_consis_addr_io_addr_start_3  (_u_axi_read_io_consis_addr_io_addr_start_3),
    .io_consis_addr_io_addr_start_4  (_u_axi_read_io_consis_addr_io_addr_start_4),
    .io_consis_addr_io_addr_start_5  (_u_axi_read_io_consis_addr_io_addr_start_5),
    .io_consis_addr_io_addr_start_6  (_u_axi_read_io_consis_addr_io_addr_start_6),
    .io_consis_addr_io_addr_start_7  (_u_axi_read_io_consis_addr_io_addr_start_7),
    .io_consis_addr_io_addr_start_8  (_u_axi_read_io_consis_addr_io_addr_start_8),
    .io_consis_addr_io_addr_start_9  (_u_axi_read_io_consis_addr_io_addr_start_9),
    .io_consis_addr_io_addr_start_10 (_u_axi_read_io_consis_addr_io_addr_start_10),
    .io_consis_addr_io_addr_start_11 (_u_axi_read_io_consis_addr_io_addr_start_11),
    .io_consis_addr_io_addr_start_12 (_u_axi_read_io_consis_addr_io_addr_start_12),
    .io_consis_addr_io_addr_start_13 (_u_axi_read_io_consis_addr_io_addr_start_13),
    .io_consis_addr_io_addr_start_14 (_u_axi_read_io_consis_addr_io_addr_start_14),
    .io_consis_addr_io_addr_start_15 (_u_axi_read_io_consis_addr_io_addr_start_15),
    .io_consis_addr_io_addr_start_16 (_u_axi_read_io_consis_addr_io_addr_start_16),
    .io_consis_addr_io_addr_start_17 (_u_axi_read_io_consis_addr_io_addr_start_17),
    .io_consis_addr_io_addr_start_18 (_u_axi_read_io_consis_addr_io_addr_start_18),
    .io_consis_addr_io_addr_start_19 (_u_axi_read_io_consis_addr_io_addr_start_19),
    .io_consis_addr_io_addr_start_20 (_u_axi_read_io_consis_addr_io_addr_start_20),
    .io_consis_addr_io_addr_start_21 (_u_axi_read_io_consis_addr_io_addr_start_21),
    .io_consis_addr_io_addr_start_22 (_u_axi_read_io_consis_addr_io_addr_start_22),
    .io_consis_addr_io_addr_start_23 (_u_axi_read_io_consis_addr_io_addr_start_23),
    .io_consis_addr_io_addr_start_24 (_u_axi_read_io_consis_addr_io_addr_start_24),
    .io_consis_addr_io_addr_start_25 (_u_axi_read_io_consis_addr_io_addr_start_25),
    .io_consis_addr_io_addr_start_26 (_u_axi_read_io_consis_addr_io_addr_start_26),
    .io_consis_addr_io_addr_start_27 (_u_axi_read_io_consis_addr_io_addr_start_27),
    .io_consis_addr_io_addr_start_28 (_u_axi_read_io_consis_addr_io_addr_start_28),
    .io_consis_addr_io_addr_start_29 (_u_axi_read_io_consis_addr_io_addr_start_29),
    .io_consis_addr_io_addr_start_30 (_u_axi_read_io_consis_addr_io_addr_start_30),
    .io_consis_addr_io_addr_start_31 (_u_axi_read_io_consis_addr_io_addr_start_31),
    .io_consis_addr_io_addr_start_32 (_u_axi_read_io_consis_addr_io_addr_start_32),
    .io_consis_addr_io_addr_end_0    (_u_axi_read_io_consis_addr_io_addr_end_0),
    .io_consis_addr_io_addr_end_1    (_u_axi_read_io_consis_addr_io_addr_end_1),
    .io_consis_addr_io_addr_end_2    (_u_axi_read_io_consis_addr_io_addr_end_2),
    .io_consis_addr_io_addr_end_3    (_u_axi_read_io_consis_addr_io_addr_end_3),
    .io_consis_addr_io_addr_end_4    (_u_axi_read_io_consis_addr_io_addr_end_4),
    .io_consis_addr_io_addr_end_5    (_u_axi_read_io_consis_addr_io_addr_end_5),
    .io_consis_addr_io_addr_end_6    (_u_axi_read_io_consis_addr_io_addr_end_6),
    .io_consis_addr_io_addr_end_7    (_u_axi_read_io_consis_addr_io_addr_end_7),
    .io_consis_addr_io_addr_end_8    (_u_axi_read_io_consis_addr_io_addr_end_8),
    .io_consis_addr_io_addr_end_9    (_u_axi_read_io_consis_addr_io_addr_end_9),
    .io_consis_addr_io_addr_end_10   (_u_axi_read_io_consis_addr_io_addr_end_10),
    .io_consis_addr_io_addr_end_11   (_u_axi_read_io_consis_addr_io_addr_end_11),
    .io_consis_addr_io_addr_end_12   (_u_axi_read_io_consis_addr_io_addr_end_12),
    .io_consis_addr_io_addr_end_13   (_u_axi_read_io_consis_addr_io_addr_end_13),
    .io_consis_addr_io_addr_end_14   (_u_axi_read_io_consis_addr_io_addr_end_14),
    .io_consis_addr_io_addr_end_15   (_u_axi_read_io_consis_addr_io_addr_end_15),
    .io_consis_addr_io_addr_end_16   (_u_axi_read_io_consis_addr_io_addr_end_16),
    .io_consis_addr_io_addr_end_17   (_u_axi_read_io_consis_addr_io_addr_end_17),
    .io_consis_addr_io_addr_end_18   (_u_axi_read_io_consis_addr_io_addr_end_18),
    .io_consis_addr_io_addr_end_19   (_u_axi_read_io_consis_addr_io_addr_end_19),
    .io_consis_addr_io_addr_end_20   (_u_axi_read_io_consis_addr_io_addr_end_20),
    .io_consis_addr_io_addr_end_21   (_u_axi_read_io_consis_addr_io_addr_end_21),
    .io_consis_addr_io_addr_end_22   (_u_axi_read_io_consis_addr_io_addr_end_22),
    .io_consis_addr_io_addr_end_23   (_u_axi_read_io_consis_addr_io_addr_end_23),
    .io_consis_addr_io_addr_end_24   (_u_axi_read_io_consis_addr_io_addr_end_24),
    .io_consis_addr_io_addr_end_25   (_u_axi_read_io_consis_addr_io_addr_end_25),
    .io_consis_addr_io_addr_end_26   (_u_axi_read_io_consis_addr_io_addr_end_26),
    .io_consis_addr_io_addr_end_27   (_u_axi_read_io_consis_addr_io_addr_end_27),
    .io_consis_addr_io_addr_end_28   (_u_axi_read_io_consis_addr_io_addr_end_28),
    .io_consis_addr_io_addr_end_29   (_u_axi_read_io_consis_addr_io_addr_end_29),
    .io_consis_addr_io_addr_end_30   (_u_axi_read_io_consis_addr_io_addr_end_30),
    .io_consis_addr_io_addr_end_31   (_u_axi_read_io_consis_addr_io_addr_end_31),
    .io_consis_addr_io_addr_end_32   (_u_axi_read_io_consis_addr_io_addr_end_32),
    .io_consis_addr_io_axi_ptr       (_u_axi_read_io_consis_addr_io_axi_ptr),
    .io_consis_addr_io_ui_ptr        (_u_axi_read_io_consis_addr_io_ui_ptr),
    .io_ui_rdcmd_counter             (io_a2uregio_uiRdCmdCnt),
    .io_axi_rdcmd_counter            (io_a2uregio_axiRdCmdCnt),
    .io_ui_rdback_counter            (io_a2uregio_uiRbCmdCnt),
    .io_apb_config_done              (io_apb_config_done)
  );
  osmc_axi_token u_axi_token (	// src/main/scala/AXI2UI/osmc_axi_top.scala:66:25
    .clock                       (clock),
    .reset                       (reset),
    .io_token_io_awtoken         (_u_axi_token_io_token_io_awtoken),
    .io_token_io_artoken         (_u_axi_token_io_token_io_artoken),
    .io_token_countio_token_awen (_u_axi_write_io_token_countio_token_awen),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_token_countio_token_aren (_u_axi_read_io_token_countio_token_aren)	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  );
  osmc_axi_consis u_axi_consis (	// src/main/scala/AXI2UI/osmc_axi_top.scala:75:26
    .clock                            (clock),
    .reset                            (reset),
    .io_consis_io_wconsis             (_u_axi_consis_io_consis_io_wconsis),
    .io_consis_io_rconsis             (_u_axi_consis_io_consis_io_rconsis),
    .io_consis_waddr_io_addr_start_0  (_u_axi_write_io_consis_addr_io_addr_start_0),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_1  (_u_axi_write_io_consis_addr_io_addr_start_1),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_2  (_u_axi_write_io_consis_addr_io_addr_start_2),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_3  (_u_axi_write_io_consis_addr_io_addr_start_3),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_4  (_u_axi_write_io_consis_addr_io_addr_start_4),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_5  (_u_axi_write_io_consis_addr_io_addr_start_5),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_6  (_u_axi_write_io_consis_addr_io_addr_start_6),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_7  (_u_axi_write_io_consis_addr_io_addr_start_7),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_8  (_u_axi_write_io_consis_addr_io_addr_start_8),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_9  (_u_axi_write_io_consis_addr_io_addr_start_9),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_10 (_u_axi_write_io_consis_addr_io_addr_start_10),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_11 (_u_axi_write_io_consis_addr_io_addr_start_11),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_12 (_u_axi_write_io_consis_addr_io_addr_start_12),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_13 (_u_axi_write_io_consis_addr_io_addr_start_13),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_14 (_u_axi_write_io_consis_addr_io_addr_start_14),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_15 (_u_axi_write_io_consis_addr_io_addr_start_15),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_16 (_u_axi_write_io_consis_addr_io_addr_start_16),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_17 (_u_axi_write_io_consis_addr_io_addr_start_17),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_18 (_u_axi_write_io_consis_addr_io_addr_start_18),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_19 (_u_axi_write_io_consis_addr_io_addr_start_19),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_20 (_u_axi_write_io_consis_addr_io_addr_start_20),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_21 (_u_axi_write_io_consis_addr_io_addr_start_21),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_22 (_u_axi_write_io_consis_addr_io_addr_start_22),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_23 (_u_axi_write_io_consis_addr_io_addr_start_23),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_24 (_u_axi_write_io_consis_addr_io_addr_start_24),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_25 (_u_axi_write_io_consis_addr_io_addr_start_25),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_26 (_u_axi_write_io_consis_addr_io_addr_start_26),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_27 (_u_axi_write_io_consis_addr_io_addr_start_27),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_28 (_u_axi_write_io_consis_addr_io_addr_start_28),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_29 (_u_axi_write_io_consis_addr_io_addr_start_29),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_30 (_u_axi_write_io_consis_addr_io_addr_start_30),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_31 (_u_axi_write_io_consis_addr_io_addr_start_31),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_start_32 (_u_axi_write_io_consis_addr_io_addr_start_32),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_0    (_u_axi_write_io_consis_addr_io_addr_end_0),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_1    (_u_axi_write_io_consis_addr_io_addr_end_1),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_2    (_u_axi_write_io_consis_addr_io_addr_end_2),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_3    (_u_axi_write_io_consis_addr_io_addr_end_3),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_4    (_u_axi_write_io_consis_addr_io_addr_end_4),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_5    (_u_axi_write_io_consis_addr_io_addr_end_5),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_6    (_u_axi_write_io_consis_addr_io_addr_end_6),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_7    (_u_axi_write_io_consis_addr_io_addr_end_7),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_8    (_u_axi_write_io_consis_addr_io_addr_end_8),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_9    (_u_axi_write_io_consis_addr_io_addr_end_9),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_10   (_u_axi_write_io_consis_addr_io_addr_end_10),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_11   (_u_axi_write_io_consis_addr_io_addr_end_11),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_12   (_u_axi_write_io_consis_addr_io_addr_end_12),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_13   (_u_axi_write_io_consis_addr_io_addr_end_13),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_14   (_u_axi_write_io_consis_addr_io_addr_end_14),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_15   (_u_axi_write_io_consis_addr_io_addr_end_15),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_16   (_u_axi_write_io_consis_addr_io_addr_end_16),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_17   (_u_axi_write_io_consis_addr_io_addr_end_17),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_18   (_u_axi_write_io_consis_addr_io_addr_end_18),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_19   (_u_axi_write_io_consis_addr_io_addr_end_19),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_20   (_u_axi_write_io_consis_addr_io_addr_end_20),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_21   (_u_axi_write_io_consis_addr_io_addr_end_21),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_22   (_u_axi_write_io_consis_addr_io_addr_end_22),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_23   (_u_axi_write_io_consis_addr_io_addr_end_23),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_24   (_u_axi_write_io_consis_addr_io_addr_end_24),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_25   (_u_axi_write_io_consis_addr_io_addr_end_25),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_26   (_u_axi_write_io_consis_addr_io_addr_end_26),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_27   (_u_axi_write_io_consis_addr_io_addr_end_27),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_28   (_u_axi_write_io_consis_addr_io_addr_end_28),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_29   (_u_axi_write_io_consis_addr_io_addr_end_29),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_30   (_u_axi_write_io_consis_addr_io_addr_end_30),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_31   (_u_axi_write_io_consis_addr_io_addr_end_31),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_addr_end_32   (_u_axi_write_io_consis_addr_io_addr_end_32),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_axi_ptr       (_u_axi_write_io_consis_addr_io_axi_ptr),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_waddr_io_ui_ptr        (_u_axi_write_io_consis_addr_io_ui_ptr),	// src/main/scala/AXI2UI/osmc_axi_top.scala:45:25
    .io_consis_raddr_io_addr_start_0  (_u_axi_read_io_consis_addr_io_addr_start_0),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_1  (_u_axi_read_io_consis_addr_io_addr_start_1),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_2  (_u_axi_read_io_consis_addr_io_addr_start_2),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_3  (_u_axi_read_io_consis_addr_io_addr_start_3),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_4  (_u_axi_read_io_consis_addr_io_addr_start_4),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_5  (_u_axi_read_io_consis_addr_io_addr_start_5),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_6  (_u_axi_read_io_consis_addr_io_addr_start_6),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_7  (_u_axi_read_io_consis_addr_io_addr_start_7),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_8  (_u_axi_read_io_consis_addr_io_addr_start_8),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_9  (_u_axi_read_io_consis_addr_io_addr_start_9),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_10 (_u_axi_read_io_consis_addr_io_addr_start_10),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_11 (_u_axi_read_io_consis_addr_io_addr_start_11),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_12 (_u_axi_read_io_consis_addr_io_addr_start_12),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_13 (_u_axi_read_io_consis_addr_io_addr_start_13),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_14 (_u_axi_read_io_consis_addr_io_addr_start_14),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_15 (_u_axi_read_io_consis_addr_io_addr_start_15),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_16 (_u_axi_read_io_consis_addr_io_addr_start_16),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_17 (_u_axi_read_io_consis_addr_io_addr_start_17),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_18 (_u_axi_read_io_consis_addr_io_addr_start_18),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_19 (_u_axi_read_io_consis_addr_io_addr_start_19),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_20 (_u_axi_read_io_consis_addr_io_addr_start_20),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_21 (_u_axi_read_io_consis_addr_io_addr_start_21),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_22 (_u_axi_read_io_consis_addr_io_addr_start_22),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_23 (_u_axi_read_io_consis_addr_io_addr_start_23),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_24 (_u_axi_read_io_consis_addr_io_addr_start_24),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_25 (_u_axi_read_io_consis_addr_io_addr_start_25),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_26 (_u_axi_read_io_consis_addr_io_addr_start_26),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_27 (_u_axi_read_io_consis_addr_io_addr_start_27),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_28 (_u_axi_read_io_consis_addr_io_addr_start_28),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_29 (_u_axi_read_io_consis_addr_io_addr_start_29),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_30 (_u_axi_read_io_consis_addr_io_addr_start_30),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_31 (_u_axi_read_io_consis_addr_io_addr_start_31),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_start_32 (_u_axi_read_io_consis_addr_io_addr_start_32),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_0    (_u_axi_read_io_consis_addr_io_addr_end_0),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_1    (_u_axi_read_io_consis_addr_io_addr_end_1),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_2    (_u_axi_read_io_consis_addr_io_addr_end_2),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_3    (_u_axi_read_io_consis_addr_io_addr_end_3),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_4    (_u_axi_read_io_consis_addr_io_addr_end_4),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_5    (_u_axi_read_io_consis_addr_io_addr_end_5),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_6    (_u_axi_read_io_consis_addr_io_addr_end_6),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_7    (_u_axi_read_io_consis_addr_io_addr_end_7),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_8    (_u_axi_read_io_consis_addr_io_addr_end_8),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_9    (_u_axi_read_io_consis_addr_io_addr_end_9),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_10   (_u_axi_read_io_consis_addr_io_addr_end_10),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_11   (_u_axi_read_io_consis_addr_io_addr_end_11),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_12   (_u_axi_read_io_consis_addr_io_addr_end_12),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_13   (_u_axi_read_io_consis_addr_io_addr_end_13),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_14   (_u_axi_read_io_consis_addr_io_addr_end_14),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_15   (_u_axi_read_io_consis_addr_io_addr_end_15),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_16   (_u_axi_read_io_consis_addr_io_addr_end_16),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_17   (_u_axi_read_io_consis_addr_io_addr_end_17),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_18   (_u_axi_read_io_consis_addr_io_addr_end_18),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_19   (_u_axi_read_io_consis_addr_io_addr_end_19),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_20   (_u_axi_read_io_consis_addr_io_addr_end_20),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_21   (_u_axi_read_io_consis_addr_io_addr_end_21),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_22   (_u_axi_read_io_consis_addr_io_addr_end_22),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_23   (_u_axi_read_io_consis_addr_io_addr_end_23),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_24   (_u_axi_read_io_consis_addr_io_addr_end_24),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_25   (_u_axi_read_io_consis_addr_io_addr_end_25),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_26   (_u_axi_read_io_consis_addr_io_addr_end_26),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_27   (_u_axi_read_io_consis_addr_io_addr_end_27),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_28   (_u_axi_read_io_consis_addr_io_addr_end_28),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_29   (_u_axi_read_io_consis_addr_io_addr_end_29),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_30   (_u_axi_read_io_consis_addr_io_addr_end_30),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_31   (_u_axi_read_io_consis_addr_io_addr_end_31),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_addr_end_32   (_u_axi_read_io_consis_addr_io_addr_end_32),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_axi_ptr       (_u_axi_read_io_consis_addr_io_axi_ptr),	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
    .io_consis_raddr_io_ui_ptr        (_u_axi_read_io_consis_addr_io_ui_ptr)	// src/main/scala/AXI2UI/osmc_axi_top.scala:56:25
  );
  assign io_bio_bresp = 2'h0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7, :45:25, :56:25
  assign io_rio_rresp = 2'h0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7, :45:25, :56:25
  assign io_ui_awio_bits_pri = 1'h0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7, :45:25, :56:25
  assign io_ui_ario_bits_pri = 1'h0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7, :45:25, :56:25
  assign io_ui_rio_ready = 1'h1;	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7, :56:25
  assign io_a2uregio_readyStall = 1'h0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7, :45:25, :56:25
  assign io_a2uregio_tokenCnt = 8'h0;	// src/main/scala/AXI2UI/osmc_axi_top.scala:29:7, :37:13
endmodule

