// Generated by CIRCT firtool-1.62.0
module osmc_axi_write_burst_clip(	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7
  input          clock,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7
                 reset,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7
  output         io_fifol1_awrio_ren,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  input  [53:0]  io_fifol1_awrio_rdata,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  input          io_fifol1_awrio_empty,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  output         io_fifol2_awwio_wen,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  output [45:0]  io_fifol2_awwio_wdata,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  input          io_fifol2_awwio_full,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  output         io_fifol1_wrio_ren,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  input  [288:0] io_fifol1_wrio_rdata,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  input          io_fifol1_wrio_empty,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  output         io_fifol2_wwio_wen,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  output [575:0] io_fifol2_wwio_wdata,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  input          io_fifol2_wwio_full,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  input  [9:0]   io_token_inio_awtoken,	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
  output         io_token_countio_token_awen	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:45:12
);

  wire              io_fifol1_awrio_ren_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:117:100
  reg  [7:0]        awlen;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:76:22
  reg  [35:0]       burst_addr_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_1;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_2;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_3;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_4;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_5;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_6;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_7;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_8;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_9;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_10;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_11;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_12;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_13;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_14;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [35:0]       burst_addr_15;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30
  reg  [7:0]        ui_cmd_counter;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:105:29
  reg               ui_cmd_counter_en;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:106:32
  wire              cmd_counter_add_cond = ui_cmd_counter_en | io_fifol1_awrio_ren_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:106:32, :109:50, :117:100
  wire [7:0]        _io_token_countio_token_awen_T_1 = ui_cmd_counter % 8'h2;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:105:29, :114:74
  assign io_fifol1_awrio_ren_0 =
    ui_cmd_counter == 8'h0 & ~io_fifol2_awwio_full & ~io_fifol1_awrio_empty
    & ~ui_cmd_counter_en;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:76:22, :105:29, :106:32, :114:33, :117:{41,77,100,102}
  wire [7:0]        _io_fifol2_awwio_wen_T_3 = (ui_cmd_counter + 8'h1) % 8'h2;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:84:23, :105:29, :114:74, :120:{69,74}
  wire              io_fifol2_awwio_wen_0 =
    ~io_fifol2_awwio_full & _io_fifol2_awwio_wen_T_3[1:0] == 2'h0 & ui_cmd_counter_en;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:75:22, :106:32, :114:33, :120:{74,87,95}
  wire [7:0]        _io_fifol2_awwio_wdata_T = ui_cmd_counter / 8'h2;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:105:29, :114:74, :122:77
  wire [15:0][35:0] _GEN =
    {{burst_addr_15},
     {burst_addr_14},
     {burst_addr_13},
     {burst_addr_12},
     {burst_addr_11},
     {burst_addr_10},
     {burst_addr_9},
     {burst_addr_8},
     {burst_addr_7},
     {burst_addr_6},
     {burst_addr_5},
     {burst_addr_4},
     {burst_addr_3},
     {burst_addr_2},
     {burst_addr_1},
     {burst_addr_0}};	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :122:29
  reg  [1:0]        data_counter;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:125:37
  reg  [255:0]      UI_data_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:126:37
  reg  [255:0]      UI_data_1;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:126:37
  reg  [31:0]       UI_data_mask_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:127:37
  reg  [31:0]       UI_data_mask_1;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:127:37
  reg               data_counter_add_cond;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:128:37
  wire              data_counter_reset_cond =
    data_counter == 2'h1 & data_counter_add_cond;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:125:37, :128:37, :131:{44,59,66}
  reg               w_ren_flag;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:139:30
  wire              io_fifol1_wrio_ren_0 =
    ~io_fifol1_wrio_empty & ~io_fifol2_wwio_full & w_ren_flag;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:139:30, :141:{31,57,78}
  wire [7:0]        _mask_slice_num_T = awlen + 8'h1;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:76:22, :84:23
  wire [15:0]       _UiCmdNum_T = {_mask_slice_num_T, 8'h0} - 16'h1;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:76:22, :84:23, :85:37
  wire              _GEN_0 = {6'h0, data_counter} >= 8'h2 - _mask_slice_num_T / 8'h2;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:84:23, :114:74, :125:37, :137:{30,44}, :145:24
  always @(posedge clock) begin	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7
    if (reset) begin	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7
      awlen <= 8'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:76:22
      burst_addr_0 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_1 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_2 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_3 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_4 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_5 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_6 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_7 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_8 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_9 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_10 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_11 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_12 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_13 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_14 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      burst_addr_15 <= 36'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:74:22, :80:30
      ui_cmd_counter <= 8'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:76:22, :105:29
      ui_cmd_counter_en <= 1'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:85:19, :106:32
      data_counter <= 2'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:75:22, :125:37
      UI_data_0 <= 256'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:126:{37,45}
      UI_data_1 <= 256'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:126:{37,45}
      UI_data_mask_0 <= 32'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:127:{37,45}
      UI_data_mask_1 <= 32'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:127:{37,45}
      data_counter_add_cond <= 1'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:85:19, :128:37
      w_ren_flag <= 1'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:85:19, :139:30
    end
    else begin	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7
      if (io_fifol1_awrio_ren_0) begin	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:117:100
        awlen <= io_fifol1_awrio_rdata[14:7];	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:76:22, :93:58
        burst_addr_0 <= io_fifol1_awrio_rdata[52:17];	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58
        burst_addr_1 <= io_fifol1_awrio_rdata[52:17] + 36'h40;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_2 <= io_fifol1_awrio_rdata[52:17] + 36'h80;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_3 <= io_fifol1_awrio_rdata[52:17] + 36'hC0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_4 <= io_fifol1_awrio_rdata[52:17] + 36'h100;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_5 <= io_fifol1_awrio_rdata[52:17] + 36'h140;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_6 <= io_fifol1_awrio_rdata[52:17] + 36'h180;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_7 <= io_fifol1_awrio_rdata[52:17] + 36'h1C0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_8 <= io_fifol1_awrio_rdata[52:17] + 36'h200;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_9 <= io_fifol1_awrio_rdata[52:17] + 36'h240;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_10 <= io_fifol1_awrio_rdata[52:17] + 36'h280;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_11 <= io_fifol1_awrio_rdata[52:17] + 36'h2C0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_12 <= io_fifol1_awrio_rdata[52:17] + 36'h300;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_13 <= io_fifol1_awrio_rdata[52:17] + 36'h340;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_14 <= io_fifol1_awrio_rdata[52:17] + 36'h380;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
        burst_addr_15 <= io_fifol1_awrio_rdata[52:17] + 36'h3C0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:80:30, :91:58, :103:173
      end
      if ({2'h0, ui_cmd_counter} == {1'h0, {1'h0, _UiCmdNum_T[15:9]} + 8'h1, 1'h0} - 10'h1
          & cmd_counter_add_cond)	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:75:22, :84:23, :85:{19,37,44,66}, :105:29, :109:50, :111:{48,72,79}
        ui_cmd_counter <= 8'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:76:22, :105:29
      else	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:111:79
        ui_cmd_counter <= ui_cmd_counter + {7'h0, cmd_counter_add_cond};	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:105:29, :109:50, :112:78
      if (ui_cmd_counter_en)	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:106:32
        ui_cmd_counter_en <= ~io_fifol2_awwio_wen_0 & ui_cmd_counter_en;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:106:32, :107:47, :120:95
      else	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:106:32
        ui_cmd_counter_en <= io_fifol1_awrio_ren_0 | ui_cmd_counter_en;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:106:32, :107:98, :117:100
      if (data_counter_reset_cond)	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:131:66
        data_counter <= 2'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:75:22, :125:37
      else	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:131:66
        data_counter <= data_counter + {1'h0, data_counter_add_cond};	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:85:19, :125:37, :128:37, :132:75
      if (_mask_slice_num_T[0]) begin	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:84:23, :135:{25,30}
        if (_GEN_0 & ~(data_counter[0])) begin	// <stdin>:408:21, src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:125:37, :126:37, :145:{24,50}, :146:31
          UI_data_0 <= 256'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:126:{37,45}
          UI_data_mask_0 <= 32'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:127:{37,45}
        end
        if (_GEN_0 & data_counter[0]) begin	// <stdin>:408:21, src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:125:37, :126:37, :145:{24,50}, :146:31
          UI_data_1 <= 256'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:126:{37,45}
          UI_data_mask_1 <= 32'h0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:127:{37,45}
        end
      end
      else if (io_fifol1_wrio_ren_0) begin	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:141:78
        UI_data_0 <= io_fifol1_wrio_rdata[288:33];	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:126:37, :150:66
        UI_data_1 <= UI_data_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:126:37
        UI_data_mask_0 <= 32'hFFFFFFFF;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:127:37, :147:43
        UI_data_mask_1 <= UI_data_mask_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:127:37
      end
      data_counter_add_cond <= io_fifol1_wrio_ren_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:128:37, :141:78
      w_ren_flag <= w_ren_flag | io_fifol1_awrio_ren_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:117:100, :139:30, :140:{27,50}
    end
  end // always @(posedge)
  assign io_fifol1_awrio_ren = io_fifol1_awrio_ren_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7, :117:100
  assign io_fifol2_awwio_wen = io_fifol2_awwio_wen_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7, :120:95
  assign io_fifol2_awwio_wdata =
    {io_token_inio_awtoken, _GEN[_io_fifol2_awwio_wdata_T[3:0]]};	// <stdin>:356:39, src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7, :122:{29,77}
  assign io_fifol1_wrio_ren = io_fifol1_wrio_ren_0;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7, :141:78
  assign io_fifol2_wwio_wen = data_counter_reset_cond;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7, :131:66
  assign io_fifol2_wwio_wdata = {UI_data_mask_0, UI_data_mask_1, UI_data_0, UI_data_1};	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7, :126:37, :127:37, :157:28
  assign io_token_countio_token_awen =
    ~io_fifol2_awwio_full & _io_token_countio_token_awen_T_1[1:0] == 2'h0
    & cmd_counter_add_cond;	// src/main/scala/AXI2UI/osmc_axi_write_burst_clip.scala:10:7, :75:22, :109:50, :114:{33,74,87,95}
endmodule

