// Generated by CIRCT firtool-1.62.0
module osmc_axi_write(
  input          clock,
                 reset,
  input  [35:0]  io_axi_awio_awaddr,
  input  [7:0]   io_axi_awio_awlen,
  input  [2:0]   io_axi_awio_awsize,
  input  [1:0]   io_axi_awio_awburst,
  input  [3:0]   io_axi_awio_awqos,
  input          io_axi_awio_awvalid,
  output         io_axi_awio_awready,
  input  [7:0]   io_axi_wio_wid,
  input          io_axi_wio_wuser,
  input  [255:0] io_axi_wio_wdata,
  input  [31:0]  io_axi_wio_wstrb,
  input          io_axi_wio_wlast,
                 io_axi_wio_wvalid,
  output         io_axi_wio_wready,
  output [7:0]   io_axi_bio_bid,
  output         io_axi_bio_buser,
                 io_axi_bio_bvalid,
  input          io_axi_bio_bready,
                 io_ui_awio_ready,
  output         io_ui_awio_valid,
  output [35:0]  io_ui_awio_bits_addr,
  output [9:0]   io_ui_awio_bits_token,
  input          io_ui_wio_ready,
  output         io_ui_wio_valid,
  output [511:0] io_ui_wio_bits_wdata,
  output [63:0]  io_ui_wio_bits_wstrb,
  input  [9:0]   io_token_inio_awtoken,
  output         io_token_countio_token_awen,
  input          io_ready_stall,
                 io_wconsis,
  output [71:0]  io_consis_addr_io_addr_start_0,
                 io_consis_addr_io_addr_start_1,
                 io_consis_addr_io_addr_start_2,
                 io_consis_addr_io_addr_start_3,
                 io_consis_addr_io_addr_start_4,
                 io_consis_addr_io_addr_start_5,
                 io_consis_addr_io_addr_start_6,
                 io_consis_addr_io_addr_start_7,
                 io_consis_addr_io_addr_start_8,
                 io_consis_addr_io_addr_start_9,
                 io_consis_addr_io_addr_start_10,
                 io_consis_addr_io_addr_start_11,
                 io_consis_addr_io_addr_start_12,
                 io_consis_addr_io_addr_start_13,
                 io_consis_addr_io_addr_start_14,
                 io_consis_addr_io_addr_start_15,
                 io_consis_addr_io_addr_start_16,
                 io_consis_addr_io_addr_start_17,
                 io_consis_addr_io_addr_start_18,
                 io_consis_addr_io_addr_start_19,
                 io_consis_addr_io_addr_start_20,
                 io_consis_addr_io_addr_start_21,
                 io_consis_addr_io_addr_start_22,
                 io_consis_addr_io_addr_start_23,
                 io_consis_addr_io_addr_start_24,
                 io_consis_addr_io_addr_start_25,
                 io_consis_addr_io_addr_start_26,
                 io_consis_addr_io_addr_start_27,
                 io_consis_addr_io_addr_start_28,
                 io_consis_addr_io_addr_start_29,
                 io_consis_addr_io_addr_start_30,
                 io_consis_addr_io_addr_start_31,
                 io_consis_addr_io_addr_start_32,
                 io_consis_addr_io_addr_end_0,
                 io_consis_addr_io_addr_end_1,
                 io_consis_addr_io_addr_end_2,
                 io_consis_addr_io_addr_end_3,
                 io_consis_addr_io_addr_end_4,
                 io_consis_addr_io_addr_end_5,
                 io_consis_addr_io_addr_end_6,
                 io_consis_addr_io_addr_end_7,
                 io_consis_addr_io_addr_end_8,
                 io_consis_addr_io_addr_end_9,
                 io_consis_addr_io_addr_end_10,
                 io_consis_addr_io_addr_end_11,
                 io_consis_addr_io_addr_end_12,
                 io_consis_addr_io_addr_end_13,
                 io_consis_addr_io_addr_end_14,
                 io_consis_addr_io_addr_end_15,
                 io_consis_addr_io_addr_end_16,
                 io_consis_addr_io_addr_end_17,
                 io_consis_addr_io_addr_end_18,
                 io_consis_addr_io_addr_end_19,
                 io_consis_addr_io_addr_end_20,
                 io_consis_addr_io_addr_end_21,
                 io_consis_addr_io_addr_end_22,
                 io_consis_addr_io_addr_end_23,
                 io_consis_addr_io_addr_end_24,
                 io_consis_addr_io_addr_end_25,
                 io_consis_addr_io_addr_end_26,
                 io_consis_addr_io_addr_end_27,
                 io_consis_addr_io_addr_end_28,
                 io_consis_addr_io_addr_end_29,
                 io_consis_addr_io_addr_end_30,
                 io_consis_addr_io_addr_end_31,
                 io_consis_addr_io_addr_end_32,
  output [4:0]   io_consis_addr_io_axi_ptr,
                 io_consis_addr_io_ui_ptr,
  output [31:0]  io_ui_wtcmd_counter,
                 io_axi_wtcmd_counter,
  input          io_apb_config_done
);

  wire         io_axi_bio_bvalid_0;
  wire         io_axi_wio_wready_0;
  wire         io_axi_awio_awready_0;
  wire         _u_axi_awb_fifo_out_io_fifo_wio_full;
  wire         _u_axi_awb_fifo_out_io_fifo_rio_empty;
  wire         _u_axi_wb_fifo_io_fifo_wio_full;
  wire [8:0]   _u_axi_wb_fifo_io_fifo_rio_rdata;
  wire         _u_axi_wb_fifo_io_fifo_rio_empty;
  wire         _u_ui_write_data_io_fifol2_wrio_ren;
  wire         _u_ui_write_cmd_io_ui_awio_valid;
  wire [35:0]  _u_ui_write_cmd_io_ui_awio_bits_addr;
  wire         _u_ui_write_cmd_io_fifol2_awrio_ren;
  wire         _u_axi_w_fifol2_io_fifo_wio_full;
  wire [575:0] _u_axi_w_fifol2_io_fifo_rio_rdata;
  wire         _u_axi_w_fifol2_io_fifo_rio_empty;
  wire         _u_axi_w_fifol1_io_fifo_wio_full;
  wire [288:0] _u_axi_w_fifol1_io_fifo_rio_rdata;
  wire         _u_axi_w_fifol1_io_fifo_rio_empty;
  wire         _u_axi_aw_fifol2_io_fifo_wio_full;
  wire [45:0]  _u_axi_aw_fifol2_io_fifo_rio_rdata;
  wire         _u_axi_aw_fifol2_io_fifo_rio_empty;
  wire         _u_axi_aw_fifol1_io_fifo_wio_full;
  wire [53:0]  _u_axi_aw_fifol1_io_fifo_rio_rdata;
  wire         _u_axi_aw_fifol1_io_fifo_rio_empty;
  wire         _u_axi_write_burst_clip_io_fifol1_awrio_ren;
  wire         _u_axi_write_burst_clip_io_fifol2_awwio_wen;
  wire [45:0]  _u_axi_write_burst_clip_io_fifol2_awwio_wdata;
  wire         _u_axi_write_burst_clip_io_fifol1_wrio_ren;
  wire         _u_axi_write_burst_clip_io_fifol2_wwio_wen;
  wire [575:0] _u_axi_write_burst_clip_io_fifol2_wwio_wdata;
  reg  [35:0]  addr0;
  reg  [7:0]   len;
  reg  [2:0]   size;
  reg  [1:0]   burst;
  reg  [3:0]   qos;
  reg          avalid;
  reg          aready;
  reg          cmd_end0;
  reg          cmd_hold;
  reg  [31:0]  axi_wtcmd_cnt;
  wire         _u_axi_aw_fifol1_io_fifo_wio_wen_T = avalid & aready;
  wire         _u_axi_aw_fifol1_io_fifo_wio_wen_T_5 =
    (_u_axi_aw_fifol1_io_fifo_wio_wen_T | cmd_hold) & ~_u_axi_aw_fifol1_io_fifo_wio_full
    & ~io_wconsis;
  wire         _u_axi_awb_fifo_out_io_fifo_rio_ren_T =
    io_axi_bio_bvalid_0 & io_axi_bio_bready;
  assign io_axi_awio_awready_0 =
    ~_u_axi_aw_fifol1_io_fifo_wio_full & ~io_wconsis & ~cmd_hold
    & ~_u_axi_awb_fifo_out_io_fifo_wio_full & io_apb_config_done;
  assign io_axi_wio_wready_0 =
    ~_u_axi_w_fifol1_io_fifo_wio_full & ~_u_axi_wb_fifo_io_fifo_wio_full
    & io_apb_config_done;
  assign io_axi_bio_bvalid_0 =
    ~_u_axi_wb_fifo_io_fifo_rio_empty & ~_u_axi_awb_fifo_out_io_fifo_rio_empty;
  wire         cmd_en = io_axi_awio_awvalid & io_axi_awio_awready_0;
  always @(posedge clock) begin
    if (reset) begin
      addr0 <= 36'h0;
      len <= 8'h0;
      size <= 3'h0;
      burst <= 2'h0;
      qos <= 4'h0;
      cmd_hold <= 1'h0;
      axi_wtcmd_cnt <= 32'h0;
    end
    else begin
      if (cmd_en) begin
        addr0 <= io_axi_awio_awaddr;
        len <= io_axi_awio_awlen;
        size <= io_axi_awio_awsize;
        burst <= io_axi_awio_awburst;
        qos <= io_axi_awio_awqos;
      end
      else if (_u_axi_aw_fifol1_io_fifo_wio_wen_T_5) begin
        addr0 <= 36'h0;
        len <= 8'h0;
        size <= 3'h0;
        burst <= 2'h0;
        qos <= 4'h0;
      end
      cmd_hold <=
        cmd_end0 & _u_axi_aw_fifol1_io_fifo_wio_full | io_wconsis & cmd_end0
        | ~_u_axi_aw_fifol1_io_fifo_wio_wen_T_5 & cmd_hold;
      if (_u_axi_aw_fifol1_io_fifo_wio_wen_T)
        axi_wtcmd_cnt <= axi_wtcmd_cnt + 32'h1;
    end
    avalid <= io_axi_awio_awvalid;
    aready <= io_axi_awio_awready_0;
    cmd_end0 <= cmd_en;
  end // always @(posedge)
  osmc_axi_write_burst_clip u_axi_write_burst_clip (
    .clock                       (clock),
    .reset                       (reset),
    .io_fifol1_awrio_ren         (_u_axi_write_burst_clip_io_fifol1_awrio_ren),
    .io_fifol1_awrio_rdata       (_u_axi_aw_fifol1_io_fifo_rio_rdata),
    .io_fifol1_awrio_empty       (_u_axi_aw_fifol1_io_fifo_rio_empty),
    .io_fifol2_awwio_wen         (_u_axi_write_burst_clip_io_fifol2_awwio_wen),
    .io_fifol2_awwio_wdata       (_u_axi_write_burst_clip_io_fifol2_awwio_wdata),
    .io_fifol2_awwio_full        (_u_axi_aw_fifol2_io_fifo_wio_full),
    .io_fifol1_wrio_ren          (_u_axi_write_burst_clip_io_fifol1_wrio_ren),
    .io_fifol1_wrio_rdata        (_u_axi_w_fifol1_io_fifo_rio_rdata),
    .io_fifol1_wrio_empty        (_u_axi_w_fifol1_io_fifo_rio_empty),
    .io_fifol2_wwio_wen          (_u_axi_write_burst_clip_io_fifol2_wwio_wen),
    .io_fifol2_wwio_wdata        (_u_axi_write_burst_clip_io_fifol2_wwio_wdata),
    .io_fifol2_wwio_full         (_u_axi_w_fifol2_io_fifo_wio_full),
    .io_token_inio_awtoken       (io_token_inio_awtoken),
    .io_token_countio_token_awen (io_token_countio_token_awen)
  );
  fwft_sync_fifo u_axi_aw_fifol1 (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (_u_axi_aw_fifol1_io_fifo_wio_wen_T_5),
    .io_fifo_wio_wdata ({1'h0, addr0, burst, len, size, qos}),
    .io_fifo_wio_full  (_u_axi_aw_fifol1_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_axi_write_burst_clip_io_fifol1_awrio_ren),
    .io_fifo_rio_rdata (_u_axi_aw_fifol1_io_fifo_rio_rdata),
    .io_fifo_rio_empty (_u_axi_aw_fifol1_io_fifo_rio_empty)
  );
  fwft_sync_fifo_1 u_axi_aw_fifol2 (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (_u_axi_write_burst_clip_io_fifol2_awwio_wen),
    .io_fifo_wio_wdata (_u_axi_write_burst_clip_io_fifol2_awwio_wdata),
    .io_fifo_wio_full  (_u_axi_aw_fifol2_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_ui_write_cmd_io_fifol2_awrio_ren),
    .io_fifo_rio_rdata (_u_axi_aw_fifol2_io_fifo_rio_rdata),
    .io_fifo_rio_empty (_u_axi_aw_fifol2_io_fifo_rio_empty)
  );
  fwft_sync_fifo_2 u_axi_w_fifol1 (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (io_axi_wio_wvalid & io_axi_wio_wready_0),
    .io_fifo_wio_wdata ({io_axi_wio_wdata, io_axi_wio_wstrb, io_axi_wio_wlast}),
    .io_fifo_wio_full  (_u_axi_w_fifol1_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_axi_write_burst_clip_io_fifol1_wrio_ren),
    .io_fifo_rio_rdata (_u_axi_w_fifol1_io_fifo_rio_rdata),
    .io_fifo_rio_empty (_u_axi_w_fifol1_io_fifo_rio_empty)
  );
  fwft_sync_fifo_3 u_axi_w_fifol2 (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (_u_axi_write_burst_clip_io_fifol2_wwio_wen),
    .io_fifo_wio_wdata (_u_axi_write_burst_clip_io_fifol2_wwio_wdata),
    .io_fifo_wio_full  (_u_axi_w_fifol2_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_ui_write_data_io_fifol2_wrio_ren),
    .io_fifo_rio_rdata (_u_axi_w_fifol2_io_fifo_rio_rdata),
    .io_fifo_rio_empty (_u_axi_w_fifol2_io_fifo_rio_empty)
  );
  osmc_ui_write_cmd u_ui_write_cmd (
    .clock                 (clock),
    .reset                 (reset),
    .io_ui_awio_ready      (io_ui_awio_ready),
    .io_ui_awio_valid      (_u_ui_write_cmd_io_ui_awio_valid),
    .io_ui_awio_bits_addr  (_u_ui_write_cmd_io_ui_awio_bits_addr),
    .io_ui_awio_bits_token (io_ui_awio_bits_token),
    .io_fifol2_awrio_ren   (_u_ui_write_cmd_io_fifol2_awrio_ren),
    .io_fifol2_awrio_rdata (_u_axi_aw_fifol2_io_fifo_rio_rdata),
    .io_fifol2_awrio_empty (_u_axi_aw_fifol2_io_fifo_rio_empty),
    .io_ready_stall        (io_ready_stall),
    .io_ui_wtcmd_counter   (io_ui_wtcmd_counter)
  );
  osmc_ui_write_data u_ui_write_data (
    .io_ui_wio_ready      (io_ui_wio_ready),
    .io_ui_wio_valid      (io_ui_wio_valid),
    .io_ui_wio_bits_wdata (io_ui_wio_bits_wdata),
    .io_ui_wio_bits_wstrb (io_ui_wio_bits_wstrb),
    .io_fifol2_wrio_ren   (_u_ui_write_data_io_fifol2_wrio_ren),
    .io_fifol2_wrio_rdata (_u_axi_w_fifol2_io_fifo_rio_rdata),
    .io_fifol2_wrio_empty (_u_axi_w_fifol2_io_fifo_rio_empty)
  );
  fwft_sync_fifo_4 u_axi_wb_fifo (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (io_axi_wio_wvalid & io_axi_wio_wlast & io_axi_wio_wready_0),
    .io_fifo_wio_wdata ({io_axi_wio_wid, io_axi_wio_wuser}),
    .io_fifo_wio_full  (_u_axi_wb_fifo_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_axi_awb_fifo_out_io_fifo_rio_ren_T),
    .io_fifo_rio_rdata (_u_axi_wb_fifo_io_fifo_rio_rdata),
    .io_fifo_rio_empty (_u_axi_wb_fifo_io_fifo_rio_empty)
  );
  fwft_sync_fifo_5 u_axi_awb_fifo_out (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (io_axi_awio_awready_0 & io_axi_awio_awvalid),
    .io_fifo_wio_full  (_u_axi_awb_fifo_out_io_fifo_wio_full),
    .io_fifo_rio_ren   (_u_axi_awb_fifo_out_io_fifo_rio_ren_T),
    .io_fifo_rio_empty (_u_axi_awb_fifo_out_io_fifo_rio_empty)
  );
  osmc_axi_consis_table w_axi_consis_table (
    .clock                           (clock),
    .reset                           (reset),
    .io_axi_aio_aaddr                (io_axi_awio_awaddr),
    .io_axi_aio_alen                 (io_axi_awio_awlen),
    .io_axi_aio_asize                (io_axi_awio_awsize),
    .io_axi_aio_avalid               (io_axi_awio_awvalid),
    .io_axi_aio_aready               (io_axi_awio_awready_0),
    .io_ui_aio_addr                  (_u_ui_write_cmd_io_ui_awio_bits_addr),
    .io_ui_hsio_ready                (io_ui_awio_ready),
    .io_ui_hsio_valid                (_u_ui_write_cmd_io_ui_awio_valid),
    .io_consis_addr_io_addr_start_0  (io_consis_addr_io_addr_start_0),
    .io_consis_addr_io_addr_start_1  (io_consis_addr_io_addr_start_1),
    .io_consis_addr_io_addr_start_2  (io_consis_addr_io_addr_start_2),
    .io_consis_addr_io_addr_start_3  (io_consis_addr_io_addr_start_3),
    .io_consis_addr_io_addr_start_4  (io_consis_addr_io_addr_start_4),
    .io_consis_addr_io_addr_start_5  (io_consis_addr_io_addr_start_5),
    .io_consis_addr_io_addr_start_6  (io_consis_addr_io_addr_start_6),
    .io_consis_addr_io_addr_start_7  (io_consis_addr_io_addr_start_7),
    .io_consis_addr_io_addr_start_8  (io_consis_addr_io_addr_start_8),
    .io_consis_addr_io_addr_start_9  (io_consis_addr_io_addr_start_9),
    .io_consis_addr_io_addr_start_10 (io_consis_addr_io_addr_start_10),
    .io_consis_addr_io_addr_start_11 (io_consis_addr_io_addr_start_11),
    .io_consis_addr_io_addr_start_12 (io_consis_addr_io_addr_start_12),
    .io_consis_addr_io_addr_start_13 (io_consis_addr_io_addr_start_13),
    .io_consis_addr_io_addr_start_14 (io_consis_addr_io_addr_start_14),
    .io_consis_addr_io_addr_start_15 (io_consis_addr_io_addr_start_15),
    .io_consis_addr_io_addr_start_16 (io_consis_addr_io_addr_start_16),
    .io_consis_addr_io_addr_start_17 (io_consis_addr_io_addr_start_17),
    .io_consis_addr_io_addr_start_18 (io_consis_addr_io_addr_start_18),
    .io_consis_addr_io_addr_start_19 (io_consis_addr_io_addr_start_19),
    .io_consis_addr_io_addr_start_20 (io_consis_addr_io_addr_start_20),
    .io_consis_addr_io_addr_start_21 (io_consis_addr_io_addr_start_21),
    .io_consis_addr_io_addr_start_22 (io_consis_addr_io_addr_start_22),
    .io_consis_addr_io_addr_start_23 (io_consis_addr_io_addr_start_23),
    .io_consis_addr_io_addr_start_24 (io_consis_addr_io_addr_start_24),
    .io_consis_addr_io_addr_start_25 (io_consis_addr_io_addr_start_25),
    .io_consis_addr_io_addr_start_26 (io_consis_addr_io_addr_start_26),
    .io_consis_addr_io_addr_start_27 (io_consis_addr_io_addr_start_27),
    .io_consis_addr_io_addr_start_28 (io_consis_addr_io_addr_start_28),
    .io_consis_addr_io_addr_start_29 (io_consis_addr_io_addr_start_29),
    .io_consis_addr_io_addr_start_30 (io_consis_addr_io_addr_start_30),
    .io_consis_addr_io_addr_start_31 (io_consis_addr_io_addr_start_31),
    .io_consis_addr_io_addr_start_32 (io_consis_addr_io_addr_start_32),
    .io_consis_addr_io_addr_end_0    (io_consis_addr_io_addr_end_0),
    .io_consis_addr_io_addr_end_1    (io_consis_addr_io_addr_end_1),
    .io_consis_addr_io_addr_end_2    (io_consis_addr_io_addr_end_2),
    .io_consis_addr_io_addr_end_3    (io_consis_addr_io_addr_end_3),
    .io_consis_addr_io_addr_end_4    (io_consis_addr_io_addr_end_4),
    .io_consis_addr_io_addr_end_5    (io_consis_addr_io_addr_end_5),
    .io_consis_addr_io_addr_end_6    (io_consis_addr_io_addr_end_6),
    .io_consis_addr_io_addr_end_7    (io_consis_addr_io_addr_end_7),
    .io_consis_addr_io_addr_end_8    (io_consis_addr_io_addr_end_8),
    .io_consis_addr_io_addr_end_9    (io_consis_addr_io_addr_end_9),
    .io_consis_addr_io_addr_end_10   (io_consis_addr_io_addr_end_10),
    .io_consis_addr_io_addr_end_11   (io_consis_addr_io_addr_end_11),
    .io_consis_addr_io_addr_end_12   (io_consis_addr_io_addr_end_12),
    .io_consis_addr_io_addr_end_13   (io_consis_addr_io_addr_end_13),
    .io_consis_addr_io_addr_end_14   (io_consis_addr_io_addr_end_14),
    .io_consis_addr_io_addr_end_15   (io_consis_addr_io_addr_end_15),
    .io_consis_addr_io_addr_end_16   (io_consis_addr_io_addr_end_16),
    .io_consis_addr_io_addr_end_17   (io_consis_addr_io_addr_end_17),
    .io_consis_addr_io_addr_end_18   (io_consis_addr_io_addr_end_18),
    .io_consis_addr_io_addr_end_19   (io_consis_addr_io_addr_end_19),
    .io_consis_addr_io_addr_end_20   (io_consis_addr_io_addr_end_20),
    .io_consis_addr_io_addr_end_21   (io_consis_addr_io_addr_end_21),
    .io_consis_addr_io_addr_end_22   (io_consis_addr_io_addr_end_22),
    .io_consis_addr_io_addr_end_23   (io_consis_addr_io_addr_end_23),
    .io_consis_addr_io_addr_end_24   (io_consis_addr_io_addr_end_24),
    .io_consis_addr_io_addr_end_25   (io_consis_addr_io_addr_end_25),
    .io_consis_addr_io_addr_end_26   (io_consis_addr_io_addr_end_26),
    .io_consis_addr_io_addr_end_27   (io_consis_addr_io_addr_end_27),
    .io_consis_addr_io_addr_end_28   (io_consis_addr_io_addr_end_28),
    .io_consis_addr_io_addr_end_29   (io_consis_addr_io_addr_end_29),
    .io_consis_addr_io_addr_end_30   (io_consis_addr_io_addr_end_30),
    .io_consis_addr_io_addr_end_31   (io_consis_addr_io_addr_end_31),
    .io_consis_addr_io_addr_end_32   (io_consis_addr_io_addr_end_32),
    .io_consis_addr_io_axi_ptr       (io_consis_addr_io_axi_ptr),
    .io_consis_addr_io_ui_ptr        (io_consis_addr_io_ui_ptr)
  );
  assign io_axi_awio_awready = io_axi_awio_awready_0;
  assign io_axi_wio_wready = io_axi_wio_wready_0;
  assign io_axi_bio_bid = _u_axi_wb_fifo_io_fifo_rio_rdata[8:1];
  assign io_axi_bio_buser = _u_axi_wb_fifo_io_fifo_rio_rdata[0];
  assign io_axi_bio_bvalid = io_axi_bio_bvalid_0;
  assign io_ui_awio_valid = _u_ui_write_cmd_io_ui_awio_valid;
  assign io_ui_awio_bits_addr = _u_ui_write_cmd_io_ui_awio_bits_addr;
  assign io_axi_wtcmd_counter = axi_wtcmd_cnt;
endmodule

