// Generated by CIRCT firtool-1.62.0
module osmc_axi_top(
  input          clock,
                 reset,
  input  [7:0]   io_awio_awid,
  input  [35:0]  io_awio_awaddr,
  input  [7:0]   io_awio_awlen,
  input  [2:0]   io_awio_awsize,
  input  [1:0]   io_awio_awburst,
  input          io_awio_awuser,
  input  [3:0]   io_awio_awqos,
  input          io_awio_awvalid,
  output         io_awio_awready,
  input  [7:0]   io_wio_wid,
  input          io_wio_wuser,
  input  [255:0] io_wio_wdata,
  input  [31:0]  io_wio_wstrb,
  input          io_wio_wlast,
                 io_wio_wvalid,
  output         io_wio_wready,
  output [7:0]   io_bio_bid,
  output [1:0]   io_bio_bresp,
  output         io_bio_buser,
                 io_bio_bvalid,
  input          io_bio_bready,
  input  [7:0]   io_ario_arid,
  input  [35:0]  io_ario_araddr,
  input  [7:0]   io_ario_arlen,
  input  [2:0]   io_ario_arsize,
  input  [1:0]   io_ario_arburst,
  input          io_ario_aruser,
  input  [3:0]   io_ario_arqos,
  input          io_ario_arvalid,
  output         io_ario_arready,
  output [7:0]   io_rio_rid,
  output         io_rio_ruser,
  output [255:0] io_rio_rdata,
  output [1:0]   io_rio_rresp,
  output         io_rio_rlast,
                 io_rio_rvalid,
  input          io_rio_rready,
                 io_ui_awio_ready,
  output         io_ui_awio_valid,
  output [35:0]  io_ui_awio_bits_addr,
  output [9:0]   io_ui_awio_bits_token,
  output         io_ui_awio_bits_pri,
  input          io_ui_wio_ready,
  output         io_ui_wio_valid,
  output [511:0] io_ui_wio_bits_wdata,
  output [63:0]  io_ui_wio_bits_wstrb,
  input          io_ui_ario_ready,
  output         io_ui_ario_valid,
  output [35:0]  io_ui_ario_bits_addr,
  output [9:0]   io_ui_ario_bits_token,
  output         io_ui_ario_bits_pri,
                 io_ui_rio_ready,
  input          io_ui_rio_valid,
  input  [511:0] io_ui_rio_bits_rdata,
  input  [9:0]   io_ui_rio_bits_rtoken,
  output [31:0]  io_a2uregio_axiRdCmdCnt,
                 io_a2uregio_axiWrCmdCnt,
                 io_a2uregio_uiRdCmdCnt,
                 io_a2uregio_uiWrCmdCnt,
                 io_a2uregio_uiRbCmdCnt,
  output         io_a2uregio_readyStall,
  output [7:0]   io_a2uregio_tokenCnt,
  input          io_apb_config_done
);

  wire        _u_axi_consis_io_consis_io_wconsis;
  wire        _u_axi_consis_io_consis_io_rconsis;
  wire [9:0]  _u_axi_token_io_token_io_awtoken;
  wire [9:0]  _u_axi_token_io_token_io_artoken;
  wire        _u_axi_read_io_token_countio_token_aren;
  wire        _u_axi_read_io_ready_stall;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_0;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_1;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_2;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_3;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_4;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_5;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_6;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_7;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_8;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_9;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_10;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_11;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_12;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_13;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_14;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_15;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_16;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_17;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_18;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_19;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_20;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_21;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_22;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_23;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_24;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_25;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_26;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_27;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_28;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_29;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_30;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_31;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_start_32;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_0;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_1;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_2;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_3;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_4;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_5;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_6;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_7;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_8;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_9;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_10;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_11;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_12;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_13;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_14;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_15;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_16;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_17;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_18;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_19;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_20;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_21;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_22;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_23;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_24;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_25;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_26;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_27;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_28;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_29;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_30;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_31;
  wire [71:0] _u_axi_read_io_consis_addr_io_addr_end_32;
  wire [4:0]  _u_axi_read_io_consis_addr_io_axi_ptr;
  wire [4:0]  _u_axi_read_io_consis_addr_io_ui_ptr;
  wire        _u_axi_write_io_token_countio_token_awen;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_0;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_1;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_2;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_3;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_4;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_5;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_6;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_7;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_8;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_9;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_10;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_11;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_12;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_13;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_14;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_15;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_16;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_17;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_18;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_19;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_20;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_21;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_22;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_23;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_24;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_25;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_26;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_27;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_28;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_29;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_30;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_31;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_start_32;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_0;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_1;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_2;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_3;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_4;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_5;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_6;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_7;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_8;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_9;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_10;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_11;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_12;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_13;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_14;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_15;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_16;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_17;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_18;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_19;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_20;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_21;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_22;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_23;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_24;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_25;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_26;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_27;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_28;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_29;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_30;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_31;
  wire [71:0] _u_axi_write_io_consis_addr_io_addr_end_32;
  wire [4:0]  _u_axi_write_io_consis_addr_io_axi_ptr;
  wire [4:0]  _u_axi_write_io_consis_addr_io_ui_ptr;
  osmc_axi_write u_axi_write (
    .clock                           (clock),
    .reset                           (reset),
    .io_axi_awio_awaddr              (io_awio_awaddr),
    .io_axi_awio_awlen               (io_awio_awlen),
    .io_axi_awio_awsize              (io_awio_awsize),
    .io_axi_awio_awburst             (io_awio_awburst),
    .io_axi_awio_awqos               (io_awio_awqos),
    .io_axi_awio_awvalid             (io_awio_awvalid),
    .io_axi_awio_awready             (io_awio_awready),
    .io_axi_wio_wid                  (io_wio_wid),
    .io_axi_wio_wuser                (io_wio_wuser),
    .io_axi_wio_wdata                (io_wio_wdata),
    .io_axi_wio_wstrb                (io_wio_wstrb),
    .io_axi_wio_wlast                (io_wio_wlast),
    .io_axi_wio_wvalid               (io_wio_wvalid),
    .io_axi_wio_wready               (io_wio_wready),
    .io_axi_bio_bid                  (io_bio_bid),
    .io_axi_bio_buser                (io_bio_buser),
    .io_axi_bio_bvalid               (io_bio_bvalid),
    .io_axi_bio_bready               (io_bio_bready),
    .io_ui_awio_ready                (io_ui_awio_ready),
    .io_ui_awio_valid                (io_ui_awio_valid),
    .io_ui_awio_bits_addr            (io_ui_awio_bits_addr),
    .io_ui_awio_bits_token           (io_ui_awio_bits_token),
    .io_ui_wio_ready                 (io_ui_wio_ready),
    .io_ui_wio_valid                 (io_ui_wio_valid),
    .io_ui_wio_bits_wdata            (io_ui_wio_bits_wdata),
    .io_ui_wio_bits_wstrb            (io_ui_wio_bits_wstrb),
    .io_token_inio_awtoken           (_u_axi_token_io_token_io_awtoken),
    .io_token_countio_token_awen     (_u_axi_write_io_token_countio_token_awen),
    .io_ready_stall                  (_u_axi_read_io_ready_stall),
    .io_wconsis                      (_u_axi_consis_io_consis_io_wconsis),
    .io_consis_addr_io_addr_start_0  (_u_axi_write_io_consis_addr_io_addr_start_0),
    .io_consis_addr_io_addr_start_1  (_u_axi_write_io_consis_addr_io_addr_start_1),
    .io_consis_addr_io_addr_start_2  (_u_axi_write_io_consis_addr_io_addr_start_2),
    .io_consis_addr_io_addr_start_3  (_u_axi_write_io_consis_addr_io_addr_start_3),
    .io_consis_addr_io_addr_start_4  (_u_axi_write_io_consis_addr_io_addr_start_4),
    .io_consis_addr_io_addr_start_5  (_u_axi_write_io_consis_addr_io_addr_start_5),
    .io_consis_addr_io_addr_start_6  (_u_axi_write_io_consis_addr_io_addr_start_6),
    .io_consis_addr_io_addr_start_7  (_u_axi_write_io_consis_addr_io_addr_start_7),
    .io_consis_addr_io_addr_start_8  (_u_axi_write_io_consis_addr_io_addr_start_8),
    .io_consis_addr_io_addr_start_9  (_u_axi_write_io_consis_addr_io_addr_start_9),
    .io_consis_addr_io_addr_start_10 (_u_axi_write_io_consis_addr_io_addr_start_10),
    .io_consis_addr_io_addr_start_11 (_u_axi_write_io_consis_addr_io_addr_start_11),
    .io_consis_addr_io_addr_start_12 (_u_axi_write_io_consis_addr_io_addr_start_12),
    .io_consis_addr_io_addr_start_13 (_u_axi_write_io_consis_addr_io_addr_start_13),
    .io_consis_addr_io_addr_start_14 (_u_axi_write_io_consis_addr_io_addr_start_14),
    .io_consis_addr_io_addr_start_15 (_u_axi_write_io_consis_addr_io_addr_start_15),
    .io_consis_addr_io_addr_start_16 (_u_axi_write_io_consis_addr_io_addr_start_16),
    .io_consis_addr_io_addr_start_17 (_u_axi_write_io_consis_addr_io_addr_start_17),
    .io_consis_addr_io_addr_start_18 (_u_axi_write_io_consis_addr_io_addr_start_18),
    .io_consis_addr_io_addr_start_19 (_u_axi_write_io_consis_addr_io_addr_start_19),
    .io_consis_addr_io_addr_start_20 (_u_axi_write_io_consis_addr_io_addr_start_20),
    .io_consis_addr_io_addr_start_21 (_u_axi_write_io_consis_addr_io_addr_start_21),
    .io_consis_addr_io_addr_start_22 (_u_axi_write_io_consis_addr_io_addr_start_22),
    .io_consis_addr_io_addr_start_23 (_u_axi_write_io_consis_addr_io_addr_start_23),
    .io_consis_addr_io_addr_start_24 (_u_axi_write_io_consis_addr_io_addr_start_24),
    .io_consis_addr_io_addr_start_25 (_u_axi_write_io_consis_addr_io_addr_start_25),
    .io_consis_addr_io_addr_start_26 (_u_axi_write_io_consis_addr_io_addr_start_26),
    .io_consis_addr_io_addr_start_27 (_u_axi_write_io_consis_addr_io_addr_start_27),
    .io_consis_addr_io_addr_start_28 (_u_axi_write_io_consis_addr_io_addr_start_28),
    .io_consis_addr_io_addr_start_29 (_u_axi_write_io_consis_addr_io_addr_start_29),
    .io_consis_addr_io_addr_start_30 (_u_axi_write_io_consis_addr_io_addr_start_30),
    .io_consis_addr_io_addr_start_31 (_u_axi_write_io_consis_addr_io_addr_start_31),
    .io_consis_addr_io_addr_start_32 (_u_axi_write_io_consis_addr_io_addr_start_32),
    .io_consis_addr_io_addr_end_0    (_u_axi_write_io_consis_addr_io_addr_end_0),
    .io_consis_addr_io_addr_end_1    (_u_axi_write_io_consis_addr_io_addr_end_1),
    .io_consis_addr_io_addr_end_2    (_u_axi_write_io_consis_addr_io_addr_end_2),
    .io_consis_addr_io_addr_end_3    (_u_axi_write_io_consis_addr_io_addr_end_3),
    .io_consis_addr_io_addr_end_4    (_u_axi_write_io_consis_addr_io_addr_end_4),
    .io_consis_addr_io_addr_end_5    (_u_axi_write_io_consis_addr_io_addr_end_5),
    .io_consis_addr_io_addr_end_6    (_u_axi_write_io_consis_addr_io_addr_end_6),
    .io_consis_addr_io_addr_end_7    (_u_axi_write_io_consis_addr_io_addr_end_7),
    .io_consis_addr_io_addr_end_8    (_u_axi_write_io_consis_addr_io_addr_end_8),
    .io_consis_addr_io_addr_end_9    (_u_axi_write_io_consis_addr_io_addr_end_9),
    .io_consis_addr_io_addr_end_10   (_u_axi_write_io_consis_addr_io_addr_end_10),
    .io_consis_addr_io_addr_end_11   (_u_axi_write_io_consis_addr_io_addr_end_11),
    .io_consis_addr_io_addr_end_12   (_u_axi_write_io_consis_addr_io_addr_end_12),
    .io_consis_addr_io_addr_end_13   (_u_axi_write_io_consis_addr_io_addr_end_13),
    .io_consis_addr_io_addr_end_14   (_u_axi_write_io_consis_addr_io_addr_end_14),
    .io_consis_addr_io_addr_end_15   (_u_axi_write_io_consis_addr_io_addr_end_15),
    .io_consis_addr_io_addr_end_16   (_u_axi_write_io_consis_addr_io_addr_end_16),
    .io_consis_addr_io_addr_end_17   (_u_axi_write_io_consis_addr_io_addr_end_17),
    .io_consis_addr_io_addr_end_18   (_u_axi_write_io_consis_addr_io_addr_end_18),
    .io_consis_addr_io_addr_end_19   (_u_axi_write_io_consis_addr_io_addr_end_19),
    .io_consis_addr_io_addr_end_20   (_u_axi_write_io_consis_addr_io_addr_end_20),
    .io_consis_addr_io_addr_end_21   (_u_axi_write_io_consis_addr_io_addr_end_21),
    .io_consis_addr_io_addr_end_22   (_u_axi_write_io_consis_addr_io_addr_end_22),
    .io_consis_addr_io_addr_end_23   (_u_axi_write_io_consis_addr_io_addr_end_23),
    .io_consis_addr_io_addr_end_24   (_u_axi_write_io_consis_addr_io_addr_end_24),
    .io_consis_addr_io_addr_end_25   (_u_axi_write_io_consis_addr_io_addr_end_25),
    .io_consis_addr_io_addr_end_26   (_u_axi_write_io_consis_addr_io_addr_end_26),
    .io_consis_addr_io_addr_end_27   (_u_axi_write_io_consis_addr_io_addr_end_27),
    .io_consis_addr_io_addr_end_28   (_u_axi_write_io_consis_addr_io_addr_end_28),
    .io_consis_addr_io_addr_end_29   (_u_axi_write_io_consis_addr_io_addr_end_29),
    .io_consis_addr_io_addr_end_30   (_u_axi_write_io_consis_addr_io_addr_end_30),
    .io_consis_addr_io_addr_end_31   (_u_axi_write_io_consis_addr_io_addr_end_31),
    .io_consis_addr_io_addr_end_32   (_u_axi_write_io_consis_addr_io_addr_end_32),
    .io_consis_addr_io_axi_ptr       (_u_axi_write_io_consis_addr_io_axi_ptr),
    .io_consis_addr_io_ui_ptr        (_u_axi_write_io_consis_addr_io_ui_ptr),
    .io_ui_wtcmd_counter             (io_a2uregio_uiWrCmdCnt),
    .io_axi_wtcmd_counter            (io_a2uregio_axiWrCmdCnt),
    .io_apb_config_done              (io_apb_config_done)
  );
  osmc_axi_read u_axi_read (
    .clock                           (clock),
    .reset                           (reset),
    .io_axi_ario_araddr              (io_ario_araddr),
    .io_axi_ario_arlen               (io_ario_arlen),
    .io_axi_ario_arsize              (io_ario_arsize),
    .io_axi_ario_arburst             (io_ario_arburst),
    .io_axi_ario_arqos               (io_ario_arqos),
    .io_axi_ario_arvalid             (io_ario_arvalid),
    .io_axi_ario_arready             (io_ario_arready),
    .io_axi_rio_rdata                (io_rio_rdata),
    .io_axi_rio_rlast                (io_rio_rlast),
    .io_axi_rio_rvalid               (io_rio_rvalid),
    .io_axi_rio_rready               (io_rio_rready),
    .io_ui_ario_ready                (io_ui_ario_ready),
    .io_ui_ario_valid                (io_ui_ario_valid),
    .io_ui_ario_bits_addr            (io_ui_ario_bits_addr),
    .io_ui_ario_bits_token           (io_ui_ario_bits_token),
    .io_ui_rio_valid                 (io_ui_rio_valid),
    .io_ui_rio_bits_rdata            (io_ui_rio_bits_rdata),
    .io_ui_rio_bits_rtoken           (io_ui_rio_bits_rtoken),
    .io_token_inio_artoken           (_u_axi_token_io_token_io_artoken),
    .io_token_countio_token_aren     (_u_axi_read_io_token_countio_token_aren),
    .io_ready_stall                  (_u_axi_read_io_ready_stall),
    .io_rconsis                      (_u_axi_consis_io_consis_io_rconsis),
    .io_consis_addr_io_addr_start_0  (_u_axi_read_io_consis_addr_io_addr_start_0),
    .io_consis_addr_io_addr_start_1  (_u_axi_read_io_consis_addr_io_addr_start_1),
    .io_consis_addr_io_addr_start_2  (_u_axi_read_io_consis_addr_io_addr_start_2),
    .io_consis_addr_io_addr_start_3  (_u_axi_read_io_consis_addr_io_addr_start_3),
    .io_consis_addr_io_addr_start_4  (_u_axi_read_io_consis_addr_io_addr_start_4),
    .io_consis_addr_io_addr_start_5  (_u_axi_read_io_consis_addr_io_addr_start_5),
    .io_consis_addr_io_addr_start_6  (_u_axi_read_io_consis_addr_io_addr_start_6),
    .io_consis_addr_io_addr_start_7  (_u_axi_read_io_consis_addr_io_addr_start_7),
    .io_consis_addr_io_addr_start_8  (_u_axi_read_io_consis_addr_io_addr_start_8),
    .io_consis_addr_io_addr_start_9  (_u_axi_read_io_consis_addr_io_addr_start_9),
    .io_consis_addr_io_addr_start_10 (_u_axi_read_io_consis_addr_io_addr_start_10),
    .io_consis_addr_io_addr_start_11 (_u_axi_read_io_consis_addr_io_addr_start_11),
    .io_consis_addr_io_addr_start_12 (_u_axi_read_io_consis_addr_io_addr_start_12),
    .io_consis_addr_io_addr_start_13 (_u_axi_read_io_consis_addr_io_addr_start_13),
    .io_consis_addr_io_addr_start_14 (_u_axi_read_io_consis_addr_io_addr_start_14),
    .io_consis_addr_io_addr_start_15 (_u_axi_read_io_consis_addr_io_addr_start_15),
    .io_consis_addr_io_addr_start_16 (_u_axi_read_io_consis_addr_io_addr_start_16),
    .io_consis_addr_io_addr_start_17 (_u_axi_read_io_consis_addr_io_addr_start_17),
    .io_consis_addr_io_addr_start_18 (_u_axi_read_io_consis_addr_io_addr_start_18),
    .io_consis_addr_io_addr_start_19 (_u_axi_read_io_consis_addr_io_addr_start_19),
    .io_consis_addr_io_addr_start_20 (_u_axi_read_io_consis_addr_io_addr_start_20),
    .io_consis_addr_io_addr_start_21 (_u_axi_read_io_consis_addr_io_addr_start_21),
    .io_consis_addr_io_addr_start_22 (_u_axi_read_io_consis_addr_io_addr_start_22),
    .io_consis_addr_io_addr_start_23 (_u_axi_read_io_consis_addr_io_addr_start_23),
    .io_consis_addr_io_addr_start_24 (_u_axi_read_io_consis_addr_io_addr_start_24),
    .io_consis_addr_io_addr_start_25 (_u_axi_read_io_consis_addr_io_addr_start_25),
    .io_consis_addr_io_addr_start_26 (_u_axi_read_io_consis_addr_io_addr_start_26),
    .io_consis_addr_io_addr_start_27 (_u_axi_read_io_consis_addr_io_addr_start_27),
    .io_consis_addr_io_addr_start_28 (_u_axi_read_io_consis_addr_io_addr_start_28),
    .io_consis_addr_io_addr_start_29 (_u_axi_read_io_consis_addr_io_addr_start_29),
    .io_consis_addr_io_addr_start_30 (_u_axi_read_io_consis_addr_io_addr_start_30),
    .io_consis_addr_io_addr_start_31 (_u_axi_read_io_consis_addr_io_addr_start_31),
    .io_consis_addr_io_addr_start_32 (_u_axi_read_io_consis_addr_io_addr_start_32),
    .io_consis_addr_io_addr_end_0    (_u_axi_read_io_consis_addr_io_addr_end_0),
    .io_consis_addr_io_addr_end_1    (_u_axi_read_io_consis_addr_io_addr_end_1),
    .io_consis_addr_io_addr_end_2    (_u_axi_read_io_consis_addr_io_addr_end_2),
    .io_consis_addr_io_addr_end_3    (_u_axi_read_io_consis_addr_io_addr_end_3),
    .io_consis_addr_io_addr_end_4    (_u_axi_read_io_consis_addr_io_addr_end_4),
    .io_consis_addr_io_addr_end_5    (_u_axi_read_io_consis_addr_io_addr_end_5),
    .io_consis_addr_io_addr_end_6    (_u_axi_read_io_consis_addr_io_addr_end_6),
    .io_consis_addr_io_addr_end_7    (_u_axi_read_io_consis_addr_io_addr_end_7),
    .io_consis_addr_io_addr_end_8    (_u_axi_read_io_consis_addr_io_addr_end_8),
    .io_consis_addr_io_addr_end_9    (_u_axi_read_io_consis_addr_io_addr_end_9),
    .io_consis_addr_io_addr_end_10   (_u_axi_read_io_consis_addr_io_addr_end_10),
    .io_consis_addr_io_addr_end_11   (_u_axi_read_io_consis_addr_io_addr_end_11),
    .io_consis_addr_io_addr_end_12   (_u_axi_read_io_consis_addr_io_addr_end_12),
    .io_consis_addr_io_addr_end_13   (_u_axi_read_io_consis_addr_io_addr_end_13),
    .io_consis_addr_io_addr_end_14   (_u_axi_read_io_consis_addr_io_addr_end_14),
    .io_consis_addr_io_addr_end_15   (_u_axi_read_io_consis_addr_io_addr_end_15),
    .io_consis_addr_io_addr_end_16   (_u_axi_read_io_consis_addr_io_addr_end_16),
    .io_consis_addr_io_addr_end_17   (_u_axi_read_io_consis_addr_io_addr_end_17),
    .io_consis_addr_io_addr_end_18   (_u_axi_read_io_consis_addr_io_addr_end_18),
    .io_consis_addr_io_addr_end_19   (_u_axi_read_io_consis_addr_io_addr_end_19),
    .io_consis_addr_io_addr_end_20   (_u_axi_read_io_consis_addr_io_addr_end_20),
    .io_consis_addr_io_addr_end_21   (_u_axi_read_io_consis_addr_io_addr_end_21),
    .io_consis_addr_io_addr_end_22   (_u_axi_read_io_consis_addr_io_addr_end_22),
    .io_consis_addr_io_addr_end_23   (_u_axi_read_io_consis_addr_io_addr_end_23),
    .io_consis_addr_io_addr_end_24   (_u_axi_read_io_consis_addr_io_addr_end_24),
    .io_consis_addr_io_addr_end_25   (_u_axi_read_io_consis_addr_io_addr_end_25),
    .io_consis_addr_io_addr_end_26   (_u_axi_read_io_consis_addr_io_addr_end_26),
    .io_consis_addr_io_addr_end_27   (_u_axi_read_io_consis_addr_io_addr_end_27),
    .io_consis_addr_io_addr_end_28   (_u_axi_read_io_consis_addr_io_addr_end_28),
    .io_consis_addr_io_addr_end_29   (_u_axi_read_io_consis_addr_io_addr_end_29),
    .io_consis_addr_io_addr_end_30   (_u_axi_read_io_consis_addr_io_addr_end_30),
    .io_consis_addr_io_addr_end_31   (_u_axi_read_io_consis_addr_io_addr_end_31),
    .io_consis_addr_io_addr_end_32   (_u_axi_read_io_consis_addr_io_addr_end_32),
    .io_consis_addr_io_axi_ptr       (_u_axi_read_io_consis_addr_io_axi_ptr),
    .io_consis_addr_io_ui_ptr        (_u_axi_read_io_consis_addr_io_ui_ptr),
    .io_ui_rdcmd_counter             (io_a2uregio_uiRdCmdCnt),
    .io_axi_rdcmd_counter            (io_a2uregio_axiRdCmdCnt),
    .io_ui_rdback_counter            (io_a2uregio_uiRbCmdCnt),
    .io_apb_config_done              (io_apb_config_done)
  );
  osmc_axi_token u_axi_token (
    .clock                       (clock),
    .reset                       (reset),
    .io_token_io_awtoken         (_u_axi_token_io_token_io_awtoken),
    .io_token_io_artoken         (_u_axi_token_io_token_io_artoken),
    .io_token_countio_token_awen (_u_axi_write_io_token_countio_token_awen),
    .io_token_countio_token_aren (_u_axi_read_io_token_countio_token_aren)
  );
  osmc_axi_consis u_axi_consis (
    .clock                            (clock),
    .reset                            (reset),
    .io_consis_io_wconsis             (_u_axi_consis_io_consis_io_wconsis),
    .io_consis_io_rconsis             (_u_axi_consis_io_consis_io_rconsis),
    .io_consis_waddr_io_addr_start_0  (_u_axi_write_io_consis_addr_io_addr_start_0),
    .io_consis_waddr_io_addr_start_1  (_u_axi_write_io_consis_addr_io_addr_start_1),
    .io_consis_waddr_io_addr_start_2  (_u_axi_write_io_consis_addr_io_addr_start_2),
    .io_consis_waddr_io_addr_start_3  (_u_axi_write_io_consis_addr_io_addr_start_3),
    .io_consis_waddr_io_addr_start_4  (_u_axi_write_io_consis_addr_io_addr_start_4),
    .io_consis_waddr_io_addr_start_5  (_u_axi_write_io_consis_addr_io_addr_start_5),
    .io_consis_waddr_io_addr_start_6  (_u_axi_write_io_consis_addr_io_addr_start_6),
    .io_consis_waddr_io_addr_start_7  (_u_axi_write_io_consis_addr_io_addr_start_7),
    .io_consis_waddr_io_addr_start_8  (_u_axi_write_io_consis_addr_io_addr_start_8),
    .io_consis_waddr_io_addr_start_9  (_u_axi_write_io_consis_addr_io_addr_start_9),
    .io_consis_waddr_io_addr_start_10 (_u_axi_write_io_consis_addr_io_addr_start_10),
    .io_consis_waddr_io_addr_start_11 (_u_axi_write_io_consis_addr_io_addr_start_11),
    .io_consis_waddr_io_addr_start_12 (_u_axi_write_io_consis_addr_io_addr_start_12),
    .io_consis_waddr_io_addr_start_13 (_u_axi_write_io_consis_addr_io_addr_start_13),
    .io_consis_waddr_io_addr_start_14 (_u_axi_write_io_consis_addr_io_addr_start_14),
    .io_consis_waddr_io_addr_start_15 (_u_axi_write_io_consis_addr_io_addr_start_15),
    .io_consis_waddr_io_addr_start_16 (_u_axi_write_io_consis_addr_io_addr_start_16),
    .io_consis_waddr_io_addr_start_17 (_u_axi_write_io_consis_addr_io_addr_start_17),
    .io_consis_waddr_io_addr_start_18 (_u_axi_write_io_consis_addr_io_addr_start_18),
    .io_consis_waddr_io_addr_start_19 (_u_axi_write_io_consis_addr_io_addr_start_19),
    .io_consis_waddr_io_addr_start_20 (_u_axi_write_io_consis_addr_io_addr_start_20),
    .io_consis_waddr_io_addr_start_21 (_u_axi_write_io_consis_addr_io_addr_start_21),
    .io_consis_waddr_io_addr_start_22 (_u_axi_write_io_consis_addr_io_addr_start_22),
    .io_consis_waddr_io_addr_start_23 (_u_axi_write_io_consis_addr_io_addr_start_23),
    .io_consis_waddr_io_addr_start_24 (_u_axi_write_io_consis_addr_io_addr_start_24),
    .io_consis_waddr_io_addr_start_25 (_u_axi_write_io_consis_addr_io_addr_start_25),
    .io_consis_waddr_io_addr_start_26 (_u_axi_write_io_consis_addr_io_addr_start_26),
    .io_consis_waddr_io_addr_start_27 (_u_axi_write_io_consis_addr_io_addr_start_27),
    .io_consis_waddr_io_addr_start_28 (_u_axi_write_io_consis_addr_io_addr_start_28),
    .io_consis_waddr_io_addr_start_29 (_u_axi_write_io_consis_addr_io_addr_start_29),
    .io_consis_waddr_io_addr_start_30 (_u_axi_write_io_consis_addr_io_addr_start_30),
    .io_consis_waddr_io_addr_start_31 (_u_axi_write_io_consis_addr_io_addr_start_31),
    .io_consis_waddr_io_addr_start_32 (_u_axi_write_io_consis_addr_io_addr_start_32),
    .io_consis_waddr_io_addr_end_0    (_u_axi_write_io_consis_addr_io_addr_end_0),
    .io_consis_waddr_io_addr_end_1    (_u_axi_write_io_consis_addr_io_addr_end_1),
    .io_consis_waddr_io_addr_end_2    (_u_axi_write_io_consis_addr_io_addr_end_2),
    .io_consis_waddr_io_addr_end_3    (_u_axi_write_io_consis_addr_io_addr_end_3),
    .io_consis_waddr_io_addr_end_4    (_u_axi_write_io_consis_addr_io_addr_end_4),
    .io_consis_waddr_io_addr_end_5    (_u_axi_write_io_consis_addr_io_addr_end_5),
    .io_consis_waddr_io_addr_end_6    (_u_axi_write_io_consis_addr_io_addr_end_6),
    .io_consis_waddr_io_addr_end_7    (_u_axi_write_io_consis_addr_io_addr_end_7),
    .io_consis_waddr_io_addr_end_8    (_u_axi_write_io_consis_addr_io_addr_end_8),
    .io_consis_waddr_io_addr_end_9    (_u_axi_write_io_consis_addr_io_addr_end_9),
    .io_consis_waddr_io_addr_end_10   (_u_axi_write_io_consis_addr_io_addr_end_10),
    .io_consis_waddr_io_addr_end_11   (_u_axi_write_io_consis_addr_io_addr_end_11),
    .io_consis_waddr_io_addr_end_12   (_u_axi_write_io_consis_addr_io_addr_end_12),
    .io_consis_waddr_io_addr_end_13   (_u_axi_write_io_consis_addr_io_addr_end_13),
    .io_consis_waddr_io_addr_end_14   (_u_axi_write_io_consis_addr_io_addr_end_14),
    .io_consis_waddr_io_addr_end_15   (_u_axi_write_io_consis_addr_io_addr_end_15),
    .io_consis_waddr_io_addr_end_16   (_u_axi_write_io_consis_addr_io_addr_end_16),
    .io_consis_waddr_io_addr_end_17   (_u_axi_write_io_consis_addr_io_addr_end_17),
    .io_consis_waddr_io_addr_end_18   (_u_axi_write_io_consis_addr_io_addr_end_18),
    .io_consis_waddr_io_addr_end_19   (_u_axi_write_io_consis_addr_io_addr_end_19),
    .io_consis_waddr_io_addr_end_20   (_u_axi_write_io_consis_addr_io_addr_end_20),
    .io_consis_waddr_io_addr_end_21   (_u_axi_write_io_consis_addr_io_addr_end_21),
    .io_consis_waddr_io_addr_end_22   (_u_axi_write_io_consis_addr_io_addr_end_22),
    .io_consis_waddr_io_addr_end_23   (_u_axi_write_io_consis_addr_io_addr_end_23),
    .io_consis_waddr_io_addr_end_24   (_u_axi_write_io_consis_addr_io_addr_end_24),
    .io_consis_waddr_io_addr_end_25   (_u_axi_write_io_consis_addr_io_addr_end_25),
    .io_consis_waddr_io_addr_end_26   (_u_axi_write_io_consis_addr_io_addr_end_26),
    .io_consis_waddr_io_addr_end_27   (_u_axi_write_io_consis_addr_io_addr_end_27),
    .io_consis_waddr_io_addr_end_28   (_u_axi_write_io_consis_addr_io_addr_end_28),
    .io_consis_waddr_io_addr_end_29   (_u_axi_write_io_consis_addr_io_addr_end_29),
    .io_consis_waddr_io_addr_end_30   (_u_axi_write_io_consis_addr_io_addr_end_30),
    .io_consis_waddr_io_addr_end_31   (_u_axi_write_io_consis_addr_io_addr_end_31),
    .io_consis_waddr_io_addr_end_32   (_u_axi_write_io_consis_addr_io_addr_end_32),
    .io_consis_waddr_io_axi_ptr       (_u_axi_write_io_consis_addr_io_axi_ptr),
    .io_consis_waddr_io_ui_ptr        (_u_axi_write_io_consis_addr_io_ui_ptr),
    .io_consis_raddr_io_addr_start_0  (_u_axi_read_io_consis_addr_io_addr_start_0),
    .io_consis_raddr_io_addr_start_1  (_u_axi_read_io_consis_addr_io_addr_start_1),
    .io_consis_raddr_io_addr_start_2  (_u_axi_read_io_consis_addr_io_addr_start_2),
    .io_consis_raddr_io_addr_start_3  (_u_axi_read_io_consis_addr_io_addr_start_3),
    .io_consis_raddr_io_addr_start_4  (_u_axi_read_io_consis_addr_io_addr_start_4),
    .io_consis_raddr_io_addr_start_5  (_u_axi_read_io_consis_addr_io_addr_start_5),
    .io_consis_raddr_io_addr_start_6  (_u_axi_read_io_consis_addr_io_addr_start_6),
    .io_consis_raddr_io_addr_start_7  (_u_axi_read_io_consis_addr_io_addr_start_7),
    .io_consis_raddr_io_addr_start_8  (_u_axi_read_io_consis_addr_io_addr_start_8),
    .io_consis_raddr_io_addr_start_9  (_u_axi_read_io_consis_addr_io_addr_start_9),
    .io_consis_raddr_io_addr_start_10 (_u_axi_read_io_consis_addr_io_addr_start_10),
    .io_consis_raddr_io_addr_start_11 (_u_axi_read_io_consis_addr_io_addr_start_11),
    .io_consis_raddr_io_addr_start_12 (_u_axi_read_io_consis_addr_io_addr_start_12),
    .io_consis_raddr_io_addr_start_13 (_u_axi_read_io_consis_addr_io_addr_start_13),
    .io_consis_raddr_io_addr_start_14 (_u_axi_read_io_consis_addr_io_addr_start_14),
    .io_consis_raddr_io_addr_start_15 (_u_axi_read_io_consis_addr_io_addr_start_15),
    .io_consis_raddr_io_addr_start_16 (_u_axi_read_io_consis_addr_io_addr_start_16),
    .io_consis_raddr_io_addr_start_17 (_u_axi_read_io_consis_addr_io_addr_start_17),
    .io_consis_raddr_io_addr_start_18 (_u_axi_read_io_consis_addr_io_addr_start_18),
    .io_consis_raddr_io_addr_start_19 (_u_axi_read_io_consis_addr_io_addr_start_19),
    .io_consis_raddr_io_addr_start_20 (_u_axi_read_io_consis_addr_io_addr_start_20),
    .io_consis_raddr_io_addr_start_21 (_u_axi_read_io_consis_addr_io_addr_start_21),
    .io_consis_raddr_io_addr_start_22 (_u_axi_read_io_consis_addr_io_addr_start_22),
    .io_consis_raddr_io_addr_start_23 (_u_axi_read_io_consis_addr_io_addr_start_23),
    .io_consis_raddr_io_addr_start_24 (_u_axi_read_io_consis_addr_io_addr_start_24),
    .io_consis_raddr_io_addr_start_25 (_u_axi_read_io_consis_addr_io_addr_start_25),
    .io_consis_raddr_io_addr_start_26 (_u_axi_read_io_consis_addr_io_addr_start_26),
    .io_consis_raddr_io_addr_start_27 (_u_axi_read_io_consis_addr_io_addr_start_27),
    .io_consis_raddr_io_addr_start_28 (_u_axi_read_io_consis_addr_io_addr_start_28),
    .io_consis_raddr_io_addr_start_29 (_u_axi_read_io_consis_addr_io_addr_start_29),
    .io_consis_raddr_io_addr_start_30 (_u_axi_read_io_consis_addr_io_addr_start_30),
    .io_consis_raddr_io_addr_start_31 (_u_axi_read_io_consis_addr_io_addr_start_31),
    .io_consis_raddr_io_addr_start_32 (_u_axi_read_io_consis_addr_io_addr_start_32),
    .io_consis_raddr_io_addr_end_0    (_u_axi_read_io_consis_addr_io_addr_end_0),
    .io_consis_raddr_io_addr_end_1    (_u_axi_read_io_consis_addr_io_addr_end_1),
    .io_consis_raddr_io_addr_end_2    (_u_axi_read_io_consis_addr_io_addr_end_2),
    .io_consis_raddr_io_addr_end_3    (_u_axi_read_io_consis_addr_io_addr_end_3),
    .io_consis_raddr_io_addr_end_4    (_u_axi_read_io_consis_addr_io_addr_end_4),
    .io_consis_raddr_io_addr_end_5    (_u_axi_read_io_consis_addr_io_addr_end_5),
    .io_consis_raddr_io_addr_end_6    (_u_axi_read_io_consis_addr_io_addr_end_6),
    .io_consis_raddr_io_addr_end_7    (_u_axi_read_io_consis_addr_io_addr_end_7),
    .io_consis_raddr_io_addr_end_8    (_u_axi_read_io_consis_addr_io_addr_end_8),
    .io_consis_raddr_io_addr_end_9    (_u_axi_read_io_consis_addr_io_addr_end_9),
    .io_consis_raddr_io_addr_end_10   (_u_axi_read_io_consis_addr_io_addr_end_10),
    .io_consis_raddr_io_addr_end_11   (_u_axi_read_io_consis_addr_io_addr_end_11),
    .io_consis_raddr_io_addr_end_12   (_u_axi_read_io_consis_addr_io_addr_end_12),
    .io_consis_raddr_io_addr_end_13   (_u_axi_read_io_consis_addr_io_addr_end_13),
    .io_consis_raddr_io_addr_end_14   (_u_axi_read_io_consis_addr_io_addr_end_14),
    .io_consis_raddr_io_addr_end_15   (_u_axi_read_io_consis_addr_io_addr_end_15),
    .io_consis_raddr_io_addr_end_16   (_u_axi_read_io_consis_addr_io_addr_end_16),
    .io_consis_raddr_io_addr_end_17   (_u_axi_read_io_consis_addr_io_addr_end_17),
    .io_consis_raddr_io_addr_end_18   (_u_axi_read_io_consis_addr_io_addr_end_18),
    .io_consis_raddr_io_addr_end_19   (_u_axi_read_io_consis_addr_io_addr_end_19),
    .io_consis_raddr_io_addr_end_20   (_u_axi_read_io_consis_addr_io_addr_end_20),
    .io_consis_raddr_io_addr_end_21   (_u_axi_read_io_consis_addr_io_addr_end_21),
    .io_consis_raddr_io_addr_end_22   (_u_axi_read_io_consis_addr_io_addr_end_22),
    .io_consis_raddr_io_addr_end_23   (_u_axi_read_io_consis_addr_io_addr_end_23),
    .io_consis_raddr_io_addr_end_24   (_u_axi_read_io_consis_addr_io_addr_end_24),
    .io_consis_raddr_io_addr_end_25   (_u_axi_read_io_consis_addr_io_addr_end_25),
    .io_consis_raddr_io_addr_end_26   (_u_axi_read_io_consis_addr_io_addr_end_26),
    .io_consis_raddr_io_addr_end_27   (_u_axi_read_io_consis_addr_io_addr_end_27),
    .io_consis_raddr_io_addr_end_28   (_u_axi_read_io_consis_addr_io_addr_end_28),
    .io_consis_raddr_io_addr_end_29   (_u_axi_read_io_consis_addr_io_addr_end_29),
    .io_consis_raddr_io_addr_end_30   (_u_axi_read_io_consis_addr_io_addr_end_30),
    .io_consis_raddr_io_addr_end_31   (_u_axi_read_io_consis_addr_io_addr_end_31),
    .io_consis_raddr_io_addr_end_32   (_u_axi_read_io_consis_addr_io_addr_end_32),
    .io_consis_raddr_io_axi_ptr       (_u_axi_read_io_consis_addr_io_axi_ptr),
    .io_consis_raddr_io_ui_ptr        (_u_axi_read_io_consis_addr_io_ui_ptr)
  );
  assign io_bio_bresp = 2'h0;
  assign io_rio_rid = 8'h0;
  assign io_rio_ruser = 1'h0;
  assign io_rio_rresp = 2'h0;
  assign io_ui_awio_bits_pri = 1'h0;
  assign io_ui_ario_bits_pri = 1'h0;
  assign io_ui_rio_ready = 1'h1;
  assign io_a2uregio_readyStall = 1'h0;
  assign io_a2uregio_tokenCnt = 8'h0;
endmodule

