// Generated by CIRCT firtool-1.62.0
module osmc_axi_read_cmd_buffer(
  input         clock,
                reset,
                io_token_fifo_rio_ren,
  output [9:0]  io_token_fifo_rio_rdata,
  input         io_token_fifo_wio_wen,
  input  [9:0]  io_token_fifo_wio_wdata,
  output        io_token_fifo_wio_full,
  input         io_cmd_fifo_rio_ren,
  output [10:0] io_cmd_fifo_rio_rdata,
  output        io_cmd_fifo_rio_empty,
  input         io_cmd_fifo_wio_wen,
  input  [10:0] io_cmd_fifo_wio_wdata,
  output        io_cmd_fifo_wio_full
);

  wire        _cmd_fifo_io_fifo_wio_full;
  wire [10:0] _cmd_fifo_io_fifo_rio_rdata;
  wire        _token_fifo_io_fifo_wio_full;
  wire [9:0]  _token_fifo_io_fifo_rio_rdata;
  reg  [10:0] cmd_rdata;
  reg  [9:0]  token_rdata;
  always @(posedge clock) begin
    if (reset) begin
      cmd_rdata <= 11'h0;
      token_rdata <= 10'h0;
    end
    else begin
      cmd_rdata <= _cmd_fifo_io_fifo_rio_rdata;
      token_rdata <= _token_fifo_io_fifo_rio_rdata;
    end
  end // always @(posedge)
  fwft_sync_fifo_9 token_fifo (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (io_token_fifo_wio_wen & ~_token_fifo_io_fifo_wio_full),
    .io_fifo_wio_wdata (io_token_fifo_wio_wdata),
    .io_fifo_wio_full  (_token_fifo_io_fifo_wio_full),
    .io_fifo_rio_ren   (io_token_fifo_rio_ren),
    .io_fifo_rio_rdata (_token_fifo_io_fifo_rio_rdata)
  );
  fwft_sync_fifo_10 cmd_fifo (
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (io_cmd_fifo_wio_wen & ~_cmd_fifo_io_fifo_wio_full),
    .io_fifo_wio_wdata (io_cmd_fifo_wio_wdata),
    .io_fifo_wio_full  (_cmd_fifo_io_fifo_wio_full),
    .io_fifo_rio_ren   (io_cmd_fifo_rio_ren),
    .io_fifo_rio_rdata (_cmd_fifo_io_fifo_rio_rdata),
    .io_fifo_rio_empty (io_cmd_fifo_rio_empty)
  );
  assign io_token_fifo_rio_rdata = token_rdata;
  assign io_token_fifo_wio_full = _token_fifo_io_fifo_wio_full;
  assign io_cmd_fifo_rio_rdata = cmd_rdata;
  assign io_cmd_fifo_wio_full = _cmd_fifo_io_fifo_wio_full;
endmodule

