// Generated by CIRCT firtool-1.62.0
module osmc_ui_write_cmd(	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7
  input         clock,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7
                reset,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7
                io_ui_awio_ready,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
  output        io_ui_awio_valid,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
  output [35:0] io_ui_awio_bits_addr,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
  output [9:0]  io_ui_awio_bits_token,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
  output        io_fifol2_awrio_ren,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
  input  [45:0] io_fifol2_awrio_rdata,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
  input         io_fifol2_awrio_empty,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
                io_ready_stall,	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
  output [31:0] io_ui_wtcmd_counter	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:32:12
);

  wire        io_ui_awio_valid_0;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:42:48
  reg  [31:0] ui_wtcmd_cnt;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:36:27
  wire        io_fifol2_awrio_ren_0 = io_ui_awio_ready & io_ui_awio_valid_0;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:42:48, src/main/scala/chisel3/util/Decoupled.scala:51:35
  assign io_ui_awio_valid_0 = ~io_fifol2_awrio_empty & ~io_ready_stall;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:42:{23,48,52}
  always @(posedge clock) begin	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7
    if (reset)	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7
      ui_wtcmd_cnt <= 32'h0;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:36:27
    else if (io_fifol2_awrio_ren_0)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      ui_wtcmd_cnt <= ui_wtcmd_cnt + 32'h1;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:36:27, :39:55
  end // always @(posedge)
  assign io_ui_awio_valid = io_ui_awio_valid_0;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7, :42:48
  assign io_ui_awio_bits_addr = io_fifol2_awrio_rdata[35:0];	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7, :43:49
  assign io_ui_awio_bits_token = io_fifol2_awrio_rdata[45:36];	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7, :44:49
  assign io_fifol2_awrio_ren = io_fifol2_awrio_ren_0;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7, src/main/scala/chisel3/util/Decoupled.scala:51:35
  assign io_ui_wtcmd_counter = ui_wtcmd_cnt;	// src/main/scala/AXI2UI/osmc_ui_write_cmd.scala:10:7, :36:27
endmodule

