// Generated by CIRCT firtool-1.62.0
module osmc_axi_consis_table(
  input         clock,
                reset,
  input  [35:0] io_axi_aio_aaddr,
  input  [7:0]  io_axi_aio_alen,
  input  [2:0]  io_axi_aio_asize,
  input         io_axi_aio_avalid,
                io_axi_aio_aready,
  input  [35:0] io_ui_aio_addr,
  input         io_ui_hsio_ready,
                io_ui_hsio_valid,
  output [71:0] io_consis_addr_io_addr_start_0,
                io_consis_addr_io_addr_start_1,
                io_consis_addr_io_addr_start_2,
                io_consis_addr_io_addr_start_3,
                io_consis_addr_io_addr_start_4,
                io_consis_addr_io_addr_start_5,
                io_consis_addr_io_addr_start_6,
                io_consis_addr_io_addr_start_7,
                io_consis_addr_io_addr_start_8,
                io_consis_addr_io_addr_start_9,
                io_consis_addr_io_addr_start_10,
                io_consis_addr_io_addr_start_11,
                io_consis_addr_io_addr_start_12,
                io_consis_addr_io_addr_start_13,
                io_consis_addr_io_addr_start_14,
                io_consis_addr_io_addr_start_15,
                io_consis_addr_io_addr_start_16,
                io_consis_addr_io_addr_start_17,
                io_consis_addr_io_addr_start_18,
                io_consis_addr_io_addr_start_19,
                io_consis_addr_io_addr_start_20,
                io_consis_addr_io_addr_start_21,
                io_consis_addr_io_addr_start_22,
                io_consis_addr_io_addr_start_23,
                io_consis_addr_io_addr_start_24,
                io_consis_addr_io_addr_start_25,
                io_consis_addr_io_addr_start_26,
                io_consis_addr_io_addr_start_27,
                io_consis_addr_io_addr_start_28,
                io_consis_addr_io_addr_start_29,
                io_consis_addr_io_addr_start_30,
                io_consis_addr_io_addr_start_31,
                io_consis_addr_io_addr_start_32,
                io_consis_addr_io_addr_end_0,
                io_consis_addr_io_addr_end_1,
                io_consis_addr_io_addr_end_2,
                io_consis_addr_io_addr_end_3,
                io_consis_addr_io_addr_end_4,
                io_consis_addr_io_addr_end_5,
                io_consis_addr_io_addr_end_6,
                io_consis_addr_io_addr_end_7,
                io_consis_addr_io_addr_end_8,
                io_consis_addr_io_addr_end_9,
                io_consis_addr_io_addr_end_10,
                io_consis_addr_io_addr_end_11,
                io_consis_addr_io_addr_end_12,
                io_consis_addr_io_addr_end_13,
                io_consis_addr_io_addr_end_14,
                io_consis_addr_io_addr_end_15,
                io_consis_addr_io_addr_end_16,
                io_consis_addr_io_addr_end_17,
                io_consis_addr_io_addr_end_18,
                io_consis_addr_io_addr_end_19,
                io_consis_addr_io_addr_end_20,
                io_consis_addr_io_addr_end_21,
                io_consis_addr_io_addr_end_22,
                io_consis_addr_io_addr_end_23,
                io_consis_addr_io_addr_end_24,
                io_consis_addr_io_addr_end_25,
                io_consis_addr_io_addr_end_26,
                io_consis_addr_io_addr_end_27,
                io_consis_addr_io_addr_end_28,
                io_consis_addr_io_addr_end_29,
                io_consis_addr_io_addr_end_30,
                io_consis_addr_io_addr_end_31,
                io_consis_addr_io_addr_end_32,
  output [4:0]  io_consis_addr_io_axi_ptr,
                io_consis_addr_io_ui_ptr
);

  reg  [4:0]        axi_ptr;
  reg  [4:0]        ui_ptr;
  wire [14:0]       _GEN = {7'h0, io_axi_aio_alen + 8'h1};
  wire [14:0]       _GEN_0 = {12'h0, io_axi_aio_asize};
  wire [35:0]       _addr0_end_T_3 = io_axi_aio_aaddr + {21'h0, _GEN << _GEN_0};
  reg  [72:0]       addr_se_memory_0;
  reg  [72:0]       addr_se_memory_1;
  reg  [72:0]       addr_se_memory_2;
  reg  [72:0]       addr_se_memory_3;
  reg  [72:0]       addr_se_memory_4;
  reg  [72:0]       addr_se_memory_5;
  reg  [72:0]       addr_se_memory_6;
  reg  [72:0]       addr_se_memory_7;
  reg  [72:0]       addr_se_memory_8;
  reg  [72:0]       addr_se_memory_9;
  reg  [72:0]       addr_se_memory_10;
  reg  [72:0]       addr_se_memory_11;
  reg  [72:0]       addr_se_memory_12;
  reg  [72:0]       addr_se_memory_13;
  reg  [72:0]       addr_se_memory_14;
  reg  [72:0]       addr_se_memory_15;
  reg  [72:0]       addr_se_memory_16;
  reg  [72:0]       addr_se_memory_17;
  reg  [72:0]       addr_se_memory_18;
  reg  [72:0]       addr_se_memory_19;
  reg  [72:0]       addr_se_memory_20;
  reg  [72:0]       addr_se_memory_21;
  reg  [72:0]       addr_se_memory_22;
  reg  [72:0]       addr_se_memory_23;
  reg  [72:0]       addr_se_memory_24;
  reg  [72:0]       addr_se_memory_25;
  reg  [72:0]       addr_se_memory_26;
  reg  [72:0]       addr_se_memory_27;
  reg  [72:0]       addr_se_memory_28;
  reg  [72:0]       addr_se_memory_29;
  reg  [72:0]       addr_se_memory_30;
  reg  [72:0]       addr_se_memory_31;
  wire [72:0]       _addr_se_memory_T =
    {_GEN << _GEN_0 > 15'h40, _addr0_end_T_3, io_axi_aio_aaddr};
  wire [31:0][72:0] _GEN_1 =
    {{addr_se_memory_31},
     {addr_se_memory_30},
     {addr_se_memory_29},
     {addr_se_memory_28},
     {addr_se_memory_27},
     {addr_se_memory_26},
     {addr_se_memory_25},
     {addr_se_memory_24},
     {addr_se_memory_23},
     {addr_se_memory_22},
     {addr_se_memory_21},
     {addr_se_memory_20},
     {addr_se_memory_19},
     {addr_se_memory_18},
     {addr_se_memory_17},
     {addr_se_memory_16},
     {addr_se_memory_15},
     {addr_se_memory_14},
     {addr_se_memory_13},
     {addr_se_memory_12},
     {addr_se_memory_11},
     {addr_se_memory_10},
     {addr_se_memory_9},
     {addr_se_memory_8},
     {addr_se_memory_7},
     {addr_se_memory_6},
     {addr_se_memory_5},
     {addr_se_memory_4},
     {addr_se_memory_3},
     {addr_se_memory_2},
     {addr_se_memory_1},
     {addr_se_memory_0}};
  wire [72:0]       _GEN_2 = _GEN_1[axi_ptr];
  wire              axi_en = io_axi_aio_avalid & io_axi_aio_aready;
  wire [72:0]       _GEN_3 = _GEN_1[ui_ptr];
  always @(posedge clock) begin
    if (reset) begin
      axi_ptr <= 5'h0;
      ui_ptr <= 5'h0;
      addr_se_memory_0 <= 73'h0;
      addr_se_memory_1 <= 73'h0;
      addr_se_memory_2 <= 73'h0;
      addr_se_memory_3 <= 73'h0;
      addr_se_memory_4 <= 73'h0;
      addr_se_memory_5 <= 73'h0;
      addr_se_memory_6 <= 73'h0;
      addr_se_memory_7 <= 73'h0;
      addr_se_memory_8 <= 73'h0;
      addr_se_memory_9 <= 73'h0;
      addr_se_memory_10 <= 73'h0;
      addr_se_memory_11 <= 73'h0;
      addr_se_memory_12 <= 73'h0;
      addr_se_memory_13 <= 73'h0;
      addr_se_memory_14 <= 73'h0;
      addr_se_memory_15 <= 73'h0;
      addr_se_memory_16 <= 73'h0;
      addr_se_memory_17 <= 73'h0;
      addr_se_memory_18 <= 73'h0;
      addr_se_memory_19 <= 73'h0;
      addr_se_memory_20 <= 73'h0;
      addr_se_memory_21 <= 73'h0;
      addr_se_memory_22 <= 73'h0;
      addr_se_memory_23 <= 73'h0;
      addr_se_memory_24 <= 73'h0;
      addr_se_memory_25 <= 73'h0;
      addr_se_memory_26 <= 73'h0;
      addr_se_memory_27 <= 73'h0;
      addr_se_memory_28 <= 73'h0;
      addr_se_memory_29 <= 73'h0;
      addr_se_memory_30 <= 73'h0;
      addr_se_memory_31 <= 73'h0;
    end
    else begin
      if (axi_en)
        axi_ptr <= axi_ptr + 5'h1;
      if (io_ui_hsio_valid & io_ui_hsio_ready
          & (~(_GEN_3[72]) & io_ui_aio_addr == _GEN_3[35:0] | _GEN_3[72]
             & io_ui_aio_addr == _GEN_3[71:36]))
        ui_ptr <= ui_ptr + 5'h1;
      if (axi_ptr == 5'h0) begin
        if (axi_en)
          addr_se_memory_0 <= _addr_se_memory_T;
        else
          addr_se_memory_0 <= _GEN_2;
      end
      if (axi_ptr == 5'h1) begin
        if (axi_en)
          addr_se_memory_1 <= _addr_se_memory_T;
        else
          addr_se_memory_1 <= _GEN_2;
      end
      if (axi_ptr == 5'h2) begin
        if (axi_en)
          addr_se_memory_2 <= _addr_se_memory_T;
        else
          addr_se_memory_2 <= _GEN_2;
      end
      if (axi_ptr == 5'h3) begin
        if (axi_en)
          addr_se_memory_3 <= _addr_se_memory_T;
        else
          addr_se_memory_3 <= _GEN_2;
      end
      if (axi_ptr == 5'h4) begin
        if (axi_en)
          addr_se_memory_4 <= _addr_se_memory_T;
        else
          addr_se_memory_4 <= _GEN_2;
      end
      if (axi_ptr == 5'h5) begin
        if (axi_en)
          addr_se_memory_5 <= _addr_se_memory_T;
        else
          addr_se_memory_5 <= _GEN_2;
      end
      if (axi_ptr == 5'h6) begin
        if (axi_en)
          addr_se_memory_6 <= _addr_se_memory_T;
        else
          addr_se_memory_6 <= _GEN_2;
      end
      if (axi_ptr == 5'h7) begin
        if (axi_en)
          addr_se_memory_7 <= _addr_se_memory_T;
        else
          addr_se_memory_7 <= _GEN_2;
      end
      if (axi_ptr == 5'h8) begin
        if (axi_en)
          addr_se_memory_8 <= _addr_se_memory_T;
        else
          addr_se_memory_8 <= _GEN_2;
      end
      if (axi_ptr == 5'h9) begin
        if (axi_en)
          addr_se_memory_9 <= _addr_se_memory_T;
        else
          addr_se_memory_9 <= _GEN_2;
      end
      if (axi_ptr == 5'hA) begin
        if (axi_en)
          addr_se_memory_10 <= _addr_se_memory_T;
        else
          addr_se_memory_10 <= _GEN_2;
      end
      if (axi_ptr == 5'hB) begin
        if (axi_en)
          addr_se_memory_11 <= _addr_se_memory_T;
        else
          addr_se_memory_11 <= _GEN_2;
      end
      if (axi_ptr == 5'hC) begin
        if (axi_en)
          addr_se_memory_12 <= _addr_se_memory_T;
        else
          addr_se_memory_12 <= _GEN_2;
      end
      if (axi_ptr == 5'hD) begin
        if (axi_en)
          addr_se_memory_13 <= _addr_se_memory_T;
        else
          addr_se_memory_13 <= _GEN_2;
      end
      if (axi_ptr == 5'hE) begin
        if (axi_en)
          addr_se_memory_14 <= _addr_se_memory_T;
        else
          addr_se_memory_14 <= _GEN_2;
      end
      if (axi_ptr == 5'hF) begin
        if (axi_en)
          addr_se_memory_15 <= _addr_se_memory_T;
        else
          addr_se_memory_15 <= _GEN_2;
      end
      if (axi_ptr == 5'h10) begin
        if (axi_en)
          addr_se_memory_16 <= _addr_se_memory_T;
        else
          addr_se_memory_16 <= _GEN_2;
      end
      if (axi_ptr == 5'h11) begin
        if (axi_en)
          addr_se_memory_17 <= _addr_se_memory_T;
        else
          addr_se_memory_17 <= _GEN_2;
      end
      if (axi_ptr == 5'h12) begin
        if (axi_en)
          addr_se_memory_18 <= _addr_se_memory_T;
        else
          addr_se_memory_18 <= _GEN_2;
      end
      if (axi_ptr == 5'h13) begin
        if (axi_en)
          addr_se_memory_19 <= _addr_se_memory_T;
        else
          addr_se_memory_19 <= _GEN_2;
      end
      if (axi_ptr == 5'h14) begin
        if (axi_en)
          addr_se_memory_20 <= _addr_se_memory_T;
        else
          addr_se_memory_20 <= _GEN_2;
      end
      if (axi_ptr == 5'h15) begin
        if (axi_en)
          addr_se_memory_21 <= _addr_se_memory_T;
        else
          addr_se_memory_21 <= _GEN_2;
      end
      if (axi_ptr == 5'h16) begin
        if (axi_en)
          addr_se_memory_22 <= _addr_se_memory_T;
        else
          addr_se_memory_22 <= _GEN_2;
      end
      if (axi_ptr == 5'h17) begin
        if (axi_en)
          addr_se_memory_23 <= _addr_se_memory_T;
        else
          addr_se_memory_23 <= _GEN_2;
      end
      if (axi_ptr == 5'h18) begin
        if (axi_en)
          addr_se_memory_24 <= _addr_se_memory_T;
        else
          addr_se_memory_24 <= _GEN_2;
      end
      if (axi_ptr == 5'h19) begin
        if (axi_en)
          addr_se_memory_25 <= _addr_se_memory_T;
        else
          addr_se_memory_25 <= _GEN_2;
      end
      if (axi_ptr == 5'h1A) begin
        if (axi_en)
          addr_se_memory_26 <= _addr_se_memory_T;
        else
          addr_se_memory_26 <= _GEN_2;
      end
      if (axi_ptr == 5'h1B) begin
        if (axi_en)
          addr_se_memory_27 <= _addr_se_memory_T;
        else
          addr_se_memory_27 <= _GEN_2;
      end
      if (axi_ptr == 5'h1C) begin
        if (axi_en)
          addr_se_memory_28 <= _addr_se_memory_T;
        else
          addr_se_memory_28 <= _GEN_2;
      end
      if (axi_ptr == 5'h1D) begin
        if (axi_en)
          addr_se_memory_29 <= _addr_se_memory_T;
        else
          addr_se_memory_29 <= _GEN_2;
      end
      if (axi_ptr == 5'h1E) begin
        if (axi_en)
          addr_se_memory_30 <= _addr_se_memory_T;
        else
          addr_se_memory_30 <= _GEN_2;
      end
      if (&axi_ptr) begin
        if (axi_en)
          addr_se_memory_31 <= _addr_se_memory_T;
        else
          addr_se_memory_31 <= _GEN_2;
      end
    end
  end // always @(posedge)
  assign io_consis_addr_io_addr_start_0 = {36'h0, io_axi_aio_aaddr};
  assign io_consis_addr_io_addr_start_1 = {36'h0, addr_se_memory_0[35:0]};
  assign io_consis_addr_io_addr_start_2 = {36'h0, addr_se_memory_1[35:0]};
  assign io_consis_addr_io_addr_start_3 = {36'h0, addr_se_memory_2[35:0]};
  assign io_consis_addr_io_addr_start_4 = {36'h0, addr_se_memory_3[35:0]};
  assign io_consis_addr_io_addr_start_5 = {36'h0, addr_se_memory_4[35:0]};
  assign io_consis_addr_io_addr_start_6 = {36'h0, addr_se_memory_5[35:0]};
  assign io_consis_addr_io_addr_start_7 = {36'h0, addr_se_memory_6[35:0]};
  assign io_consis_addr_io_addr_start_8 = {36'h0, addr_se_memory_7[35:0]};
  assign io_consis_addr_io_addr_start_9 = {36'h0, addr_se_memory_8[35:0]};
  assign io_consis_addr_io_addr_start_10 = {36'h0, addr_se_memory_9[35:0]};
  assign io_consis_addr_io_addr_start_11 = {36'h0, addr_se_memory_10[35:0]};
  assign io_consis_addr_io_addr_start_12 = {36'h0, addr_se_memory_11[35:0]};
  assign io_consis_addr_io_addr_start_13 = {36'h0, addr_se_memory_12[35:0]};
  assign io_consis_addr_io_addr_start_14 = {36'h0, addr_se_memory_13[35:0]};
  assign io_consis_addr_io_addr_start_15 = {36'h0, addr_se_memory_14[35:0]};
  assign io_consis_addr_io_addr_start_16 = {36'h0, addr_se_memory_15[35:0]};
  assign io_consis_addr_io_addr_start_17 = {36'h0, addr_se_memory_16[35:0]};
  assign io_consis_addr_io_addr_start_18 = {36'h0, addr_se_memory_17[35:0]};
  assign io_consis_addr_io_addr_start_19 = {36'h0, addr_se_memory_18[35:0]};
  assign io_consis_addr_io_addr_start_20 = {36'h0, addr_se_memory_19[35:0]};
  assign io_consis_addr_io_addr_start_21 = {36'h0, addr_se_memory_20[35:0]};
  assign io_consis_addr_io_addr_start_22 = {36'h0, addr_se_memory_21[35:0]};
  assign io_consis_addr_io_addr_start_23 = {36'h0, addr_se_memory_22[35:0]};
  assign io_consis_addr_io_addr_start_24 = {36'h0, addr_se_memory_23[35:0]};
  assign io_consis_addr_io_addr_start_25 = {36'h0, addr_se_memory_24[35:0]};
  assign io_consis_addr_io_addr_start_26 = {36'h0, addr_se_memory_25[35:0]};
  assign io_consis_addr_io_addr_start_27 = {36'h0, addr_se_memory_26[35:0]};
  assign io_consis_addr_io_addr_start_28 = {36'h0, addr_se_memory_27[35:0]};
  assign io_consis_addr_io_addr_start_29 = {36'h0, addr_se_memory_28[35:0]};
  assign io_consis_addr_io_addr_start_30 = {36'h0, addr_se_memory_29[35:0]};
  assign io_consis_addr_io_addr_start_31 = {36'h0, addr_se_memory_30[35:0]};
  assign io_consis_addr_io_addr_start_32 = {36'h0, addr_se_memory_31[35:0]};
  assign io_consis_addr_io_addr_end_0 = {36'h0, _addr0_end_T_3};
  assign io_consis_addr_io_addr_end_1 = {36'h0, addr_se_memory_0[71:36]};
  assign io_consis_addr_io_addr_end_2 = {36'h0, addr_se_memory_1[71:36]};
  assign io_consis_addr_io_addr_end_3 = {36'h0, addr_se_memory_2[71:36]};
  assign io_consis_addr_io_addr_end_4 = {36'h0, addr_se_memory_3[71:36]};
  assign io_consis_addr_io_addr_end_5 = {36'h0, addr_se_memory_4[71:36]};
  assign io_consis_addr_io_addr_end_6 = {36'h0, addr_se_memory_5[71:36]};
  assign io_consis_addr_io_addr_end_7 = {36'h0, addr_se_memory_6[71:36]};
  assign io_consis_addr_io_addr_end_8 = {36'h0, addr_se_memory_7[71:36]};
  assign io_consis_addr_io_addr_end_9 = {36'h0, addr_se_memory_8[71:36]};
  assign io_consis_addr_io_addr_end_10 = {36'h0, addr_se_memory_9[71:36]};
  assign io_consis_addr_io_addr_end_11 = {36'h0, addr_se_memory_10[71:36]};
  assign io_consis_addr_io_addr_end_12 = {36'h0, addr_se_memory_11[71:36]};
  assign io_consis_addr_io_addr_end_13 = {36'h0, addr_se_memory_12[71:36]};
  assign io_consis_addr_io_addr_end_14 = {36'h0, addr_se_memory_13[71:36]};
  assign io_consis_addr_io_addr_end_15 = {36'h0, addr_se_memory_14[71:36]};
  assign io_consis_addr_io_addr_end_16 = {36'h0, addr_se_memory_15[71:36]};
  assign io_consis_addr_io_addr_end_17 = {36'h0, addr_se_memory_16[71:36]};
  assign io_consis_addr_io_addr_end_18 = {36'h0, addr_se_memory_17[71:36]};
  assign io_consis_addr_io_addr_end_19 = {36'h0, addr_se_memory_18[71:36]};
  assign io_consis_addr_io_addr_end_20 = {36'h0, addr_se_memory_19[71:36]};
  assign io_consis_addr_io_addr_end_21 = {36'h0, addr_se_memory_20[71:36]};
  assign io_consis_addr_io_addr_end_22 = {36'h0, addr_se_memory_21[71:36]};
  assign io_consis_addr_io_addr_end_23 = {36'h0, addr_se_memory_22[71:36]};
  assign io_consis_addr_io_addr_end_24 = {36'h0, addr_se_memory_23[71:36]};
  assign io_consis_addr_io_addr_end_25 = {36'h0, addr_se_memory_24[71:36]};
  assign io_consis_addr_io_addr_end_26 = {36'h0, addr_se_memory_25[71:36]};
  assign io_consis_addr_io_addr_end_27 = {36'h0, addr_se_memory_26[71:36]};
  assign io_consis_addr_io_addr_end_28 = {36'h0, addr_se_memory_27[71:36]};
  assign io_consis_addr_io_addr_end_29 = {36'h0, addr_se_memory_28[71:36]};
  assign io_consis_addr_io_addr_end_30 = {36'h0, addr_se_memory_29[71:36]};
  assign io_consis_addr_io_addr_end_31 = {36'h0, addr_se_memory_30[71:36]};
  assign io_consis_addr_io_addr_end_32 = {36'h0, addr_se_memory_31[71:36]};
  assign io_consis_addr_io_axi_ptr = axi_ptr;
  assign io_consis_addr_io_ui_ptr = ui_ptr;
endmodule

