// Generated by CIRCT firtool-1.62.0
module osmc_ui_write_cmd(
  input         clock,
                reset,
                io_ui_awio_ready,
  output        io_ui_awio_valid,
  output [35:0] io_ui_awio_bits_addr,
  output [9:0]  io_ui_awio_bits_token,
  output        io_fifol2_awrio_ren,
  input  [45:0] io_fifol2_awrio_rdata,
  input         io_fifol2_awrio_empty,
                io_ready_stall,
  output [31:0] io_ui_wtcmd_counter
);

  wire        io_ui_awio_valid_0;
  reg  [31:0] ui_wtcmd_cnt;
  wire        io_fifol2_awrio_ren_0 = io_ui_awio_ready & io_ui_awio_valid_0;
  assign io_ui_awio_valid_0 = ~io_fifol2_awrio_empty & ~io_ready_stall;
  always @(posedge clock) begin
    if (reset)
      ui_wtcmd_cnt <= 32'h0;
    else if (io_fifol2_awrio_ren_0)
      ui_wtcmd_cnt <= ui_wtcmd_cnt + 32'h1;
  end // always @(posedge)
  assign io_ui_awio_valid = io_ui_awio_valid_0;
  assign io_ui_awio_bits_addr = io_fifol2_awrio_rdata[35:0];
  assign io_ui_awio_bits_token = io_fifol2_awrio_rdata[45:36];
  assign io_fifol2_awrio_ren = io_fifol2_awrio_ren_0;
  assign io_ui_wtcmd_counter = ui_wtcmd_cnt;
endmodule

