// Generated by CIRCT firtool-1.62.0
module osmc_axi_token(	// src/main/scala/AXI2UI/osmc_axi_token.scala:14:7
  input        clock,	// src/main/scala/AXI2UI/osmc_axi_token.scala:14:7
               reset,	// src/main/scala/AXI2UI/osmc_axi_token.scala:14:7
  output [9:0] io_token_io_awtoken,	// src/main/scala/AXI2UI/osmc_axi_token.scala:19:12
               io_token_io_artoken,	// src/main/scala/AXI2UI/osmc_axi_token.scala:19:12
  input        io_token_countio_token_awen,	// src/main/scala/AXI2UI/osmc_axi_token.scala:19:12
               io_token_countio_token_aren	// src/main/scala/AXI2UI/osmc_axi_token.scala:19:12
);

  wire [9:0] ar_token_nxt;	// src/main/scala/AXI2UI/osmc_axi_token.scala:96:27
  wire       _u_ar_token_fifo_io_fifo_rio_empty;	// src/main/scala/AXI2UI/osmc_axi_token.scala:62:30
  wire       _u_aw_token_fifo_io_fifo_rio_empty;	// src/main/scala/AXI2UI/osmc_axi_token.scala:58:30
  reg  [8:0] aw_counter;	// src/main/scala/AXI2UI/osmc_axi_token.scala:31:26
  reg  [8:0] ar_counter;	// src/main/scala/AXI2UI/osmc_axi_token.scala:32:26
  reg        aw_en_reg;	// src/main/scala/AXI2UI/osmc_axi_token.scala:41:26
  reg        ar_en_reg;	// src/main/scala/AXI2UI/osmc_axi_token.scala:42:26
  reg        aw_fullflag;	// src/main/scala/AXI2UI/osmc_axi_token.scala:47:26
  reg        ar_fullflag;	// src/main/scala/AXI2UI/osmc_axi_token.scala:48:26
  wire       aw_full = &aw_counter;	// src/main/scala/AXI2UI/osmc_axi_token.scala:31:26, :34:19, :70:24
  wire       ar_full = &ar_counter;	// src/main/scala/AXI2UI/osmc_axi_token.scala:32:26, :36:19, :71:24
  wire [1:0] _GEN = {aw_fullflag, ar_fullflag};	// src/main/scala/AXI2UI/osmc_axi_token.scala:47:26, :48:26, :79:11
  wire       full_flag = ~(_GEN == 2'h0 | (&_GEN)) & (_GEN == 2'h1 | _GEN == 2'h2);	// src/main/scala/AXI2UI/osmc_axi_token.scala:79:{11,37}, :81:20
  wire [9:0] _GEN_0 = {1'h0, aw_counter};	// src/main/scala/AXI2UI/osmc_axi_token.scala:31:26, :47:26, :95:53
  wire [9:0] _GEN_1 = {1'h0, ar_counter};	// src/main/scala/AXI2UI/osmc_axi_token.scala:32:26, :47:26, :95:68
  assign ar_token_nxt = full_flag ? _GEN_1 + _GEN_0 - 10'h200 : _GEN_1 + _GEN_0;	// src/main/scala/AXI2UI/osmc_axi_token.scala:79:37, :81:20, :95:{53,68}, :96:{27,68,106}
  always @(posedge clock) begin	// src/main/scala/AXI2UI/osmc_axi_token.scala:14:7
    if (reset) begin	// src/main/scala/AXI2UI/osmc_axi_token.scala:14:7
      aw_counter <= 9'h0;	// src/main/scala/AXI2UI/osmc_axi_token.scala:31:26
      ar_counter <= 9'h0;	// src/main/scala/AXI2UI/osmc_axi_token.scala:31:26, :32:26
      aw_fullflag <= 1'h0;	// src/main/scala/AXI2UI/osmc_axi_token.scala:47:26
      ar_fullflag <= 1'h0;	// src/main/scala/AXI2UI/osmc_axi_token.scala:47:26, :48:26
    end
    else begin	// src/main/scala/AXI2UI/osmc_axi_token.scala:14:7
      if (io_token_countio_token_awen)	// src/main/scala/AXI2UI/osmc_axi_token.scala:19:12
        aw_counter <= aw_counter + 9'h1;	// src/main/scala/AXI2UI/osmc_axi_token.scala:31:26, :88:38
      if (io_token_countio_token_aren)	// src/main/scala/AXI2UI/osmc_axi_token.scala:19:12
        ar_counter <= ar_counter + 9'h1;	// src/main/scala/AXI2UI/osmc_axi_token.scala:32:26, :88:38, :89:38
      aw_fullflag <= aw_full & io_token_countio_token_awen ^ aw_fullflag;	// src/main/scala/AXI2UI/osmc_axi_token.scala:34:19, :47:26, :73:{20,28}
      ar_fullflag <= ar_full & io_token_countio_token_aren ^ ar_fullflag;	// src/main/scala/AXI2UI/osmc_axi_token.scala:36:19, :48:26, :74:{20,28}
    end
    aw_en_reg <= io_token_countio_token_awen;	// src/main/scala/AXI2UI/osmc_axi_token.scala:41:26
    ar_en_reg <= io_token_countio_token_aren;	// src/main/scala/AXI2UI/osmc_axi_token.scala:42:26
  end // always @(posedge)
  fwft_sync_fifo_11 u_aw_token_fifo (	// src/main/scala/AXI2UI/osmc_axi_token.scala:58:30
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (aw_en_reg),	// src/main/scala/AXI2UI/osmc_axi_token.scala:41:26
    .io_fifo_wio_wdata (full_flag ? _GEN_0 + _GEN_1 - 10'h200 : _GEN_0 + _GEN_1),	// src/main/scala/AXI2UI/osmc_axi_token.scala:79:37, :81:20, :95:{27,53,68,106}
    .io_fifo_rio_ren   (~_u_aw_token_fifo_io_fifo_rio_empty),	// src/main/scala/AXI2UI/osmc_axi_token.scala:58:30, :61:45
    .io_fifo_rio_rdata (io_token_io_awtoken),
    .io_fifo_rio_empty (_u_aw_token_fifo_io_fifo_rio_empty)
  );
  fwft_sync_fifo_11 u_ar_token_fifo (	// src/main/scala/AXI2UI/osmc_axi_token.scala:62:30
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (ar_en_reg),	// src/main/scala/AXI2UI/osmc_axi_token.scala:42:26
    .io_fifo_wio_wdata (aw_en_reg & ar_en_reg ? ar_token_nxt - 10'h1 : ar_token_nxt),	// src/main/scala/AXI2UI/osmc_axi_token.scala:41:26, :42:26, :91:32, :93:{24,51}, :96:27
    .io_fifo_rio_ren   (~_u_ar_token_fifo_io_fifo_rio_empty),	// src/main/scala/AXI2UI/osmc_axi_token.scala:62:30, :65:45
    .io_fifo_rio_rdata (io_token_io_artoken),
    .io_fifo_rio_empty (_u_ar_token_fifo_io_fifo_rio_empty)
  );
endmodule

