// Generated by CIRCT firtool-1.62.0
module osmc_axi_read_cmd_buffer(	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7
  input         clock,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7
                reset,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7
                io_token_fifo_rio_ren,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  output [9:0]  io_token_fifo_rio_rdata,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  input         io_token_fifo_wio_wen,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  input  [9:0]  io_token_fifo_wio_wdata,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  output        io_token_fifo_wio_full,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  input         io_cmd_fifo_rio_ren,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  output [10:0] io_cmd_fifo_rio_rdata,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  output        io_cmd_fifo_rio_empty,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  input         io_cmd_fifo_wio_wen,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  input  [10:0] io_cmd_fifo_wio_wdata,	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
  output        io_cmd_fifo_wio_full	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:28:12
);

  wire        _cmd_fifo_io_fifo_wio_full;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:48:27
  wire [10:0] _cmd_fifo_io_fifo_rio_rdata;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:48:27
  wire        _token_fifo_io_fifo_wio_full;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:38:27
  wire [9:0]  _token_fifo_io_fifo_rio_rdata;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:38:27
  reg  [10:0] cmd_rdata;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:33:26
  reg  [9:0]  token_rdata;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:35:26
  always @(posedge clock) begin	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7
    if (reset) begin	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7
      cmd_rdata <= 11'h0;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:33:26
      token_rdata <= 10'h0;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:35:26
    end
    else begin	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7
      cmd_rdata <= _cmd_fifo_io_fifo_rio_rdata;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:33:26, :48:27
      token_rdata <= _token_fifo_io_fifo_rio_rdata;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:35:26, :38:27
    end
  end // always @(posedge)
  fwft_sync_fifo_9 token_fifo (	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:38:27
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (io_token_fifo_wio_wen & ~_token_fifo_io_fifo_wio_full),	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:38:27, :39:{60,63}
    .io_fifo_wio_wdata (io_token_fifo_wio_wdata),
    .io_fifo_wio_full  (_token_fifo_io_fifo_wio_full),
    .io_fifo_rio_ren   (io_token_fifo_rio_ren),
    .io_fifo_rio_rdata (_token_fifo_io_fifo_rio_rdata)
  );
  fwft_sync_fifo_10 cmd_fifo (	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:48:27
    .clock             (clock),
    .reset             (reset),
    .io_fifo_wio_wen   (io_cmd_fifo_wio_wen & ~_cmd_fifo_io_fifo_wio_full),	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:48:27, :49:{56,59}
    .io_fifo_wio_wdata (io_cmd_fifo_wio_wdata),
    .io_fifo_wio_full  (_cmd_fifo_io_fifo_wio_full),
    .io_fifo_rio_ren   (io_cmd_fifo_rio_ren),
    .io_fifo_rio_rdata (_cmd_fifo_io_fifo_rio_rdata),
    .io_fifo_rio_empty (io_cmd_fifo_rio_empty)
  );
  assign io_token_fifo_rio_rdata = token_rdata;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7, :35:26
  assign io_token_fifo_wio_full = _token_fifo_io_fifo_wio_full;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7, :38:27
  assign io_cmd_fifo_rio_rdata = cmd_rdata;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7, :33:26
  assign io_cmd_fifo_wio_full = _cmd_fifo_io_fifo_wio_full;	// src/main/scala/AXI2UI/osmc_axi_read_cmd_buffer.scala:11:7, :48:27
endmodule

